import type { SupplementalSourcePassage } from "./types";

/**
 * Generated from the user-provided MSMARCO-XI processed corpus using
 * scripts/build_compact_corpus_slice.py. Every text value below is a
 * verbatim source passage; this module contains no generated answers.
 */
export const EXPANDED_COMPACT_SOURCE_PASSAGES: SupplementalSourcePassage[] = [
  {
    sourceQueryId: 1185869,
    passageId: "hi_p_000000",
    language: "hi",
    content: "वैज्ञानिक दिमाग के बीच संचार की उपस्थिति मैनहट्टन परियोजना की सफलता के लिए उतनी ही महत्वपूर्ण थी जितनी कि वैज्ञानिक बुद्धिमत्ता थी। परमाणु शोधकर्ताओं और इंजीनियरों की प्रभावशाली उपलब्धि पर लटकता एकमात्र बादल उनकी सफलता का वास्तव में क्या अर्थ था; सैकड़ों हजारों निर्दोष जीवन का विनाश।",
  },
  {
    sourceQueryId: 669148,
    passageId: "hi_p_001279",
    language: "hi",
    content: "जादुई प्राणियों पर विश्व प्राधिकरण के रूप में माना जाने वाला, न्यूट स्कैमैंडर फैंटास्टिक बीस्ट्स एंड व्हेयर टू फाइंड थेम के लेखक हैं, जो 1927 में अपने प्रकाशन के बाद से हॉगवर्ट्स में एक अनुमोदित पाठ्यपुस्तक रही है और अधिकांश जादूगर घरों में पाई जा सकती है।",
  },
  {
    sourceQueryId: 1164695,
    passageId: "hi_p_002559",
    language: "hi",
    content: "प्रोस्टेट के बढ़ने के कई अलग-अलग कारण हो सकते हैं। 1. बढ़े हुए प्रोस्टेट के कारणों में शामिल हो सकते हैं: 2. सौम्य प्रोस्टेटिक हाइपरप्लासिया (बीपीएच) 3. प्रोस्टेट कैंसर 4. प्रोस्टेटाइटिस।",
  },
  {
    sourceQueryId: 1173733,
    passageId: "hi_p_003907",
    language: "hi",
    content: "शाखा की परिभाषा, पेड़ की एक शाखा, विशेष रूप से बड़ी या मुख्य शाखाओं में से एक को देखें।",
  },
  {
    sourceQueryId: 720466,
    passageId: "hi_p_004968",
    language: "hi",
    content: "खगोल विज्ञान क्या है? खगोल विज्ञान ब्रह्मांड का अध्ययन है, अर्थात् हम जिन वस्तुओं का अवलोकन करते हैं, जैसे हमारे सौर मंडल में चंद्रमा, सूर्य और ग्रह; तारे; हमारी आकाशगंगा, और अन्य आकाशगंगाएँ; और, कई अन्य खगोलीय वस्तुओं और घटनाओं, जैसे निहारिकाएँ और ब्लैक होल! हबल अंतरिक्ष दूरबीन छवियाँ।",
  },
  {
    sourceQueryId: 243321,
    passageId: "hi_p_006214",
    language: "hi",
    content: "प्रारंभिक कार पट्टा समाप्ति। आपने एक कार पट्टे पर लेने का फैसला किया। फिर, एक या दो साल के बाद, आपके पट्टे के समझौते में कुछ बदलाव होता है। आपको अपने पट्टे से जल्दी बाहर निकलना होगा। सच्चाई यह है कि कोई भी अपने पट्टे को किसी भी समय समाप्त कर सकता है - आपको बस इसके परिणामों को जानने की आवश्यकता है। यदि आप सही कदम उठाते हैं, तो आप अपने पट्टे को जल्दी समाप्त कर सकते हैं और महंगे जुर्माने से बच सकते हैं।",
  },
  {
    sourceQueryId: 756426,
    passageId: "hi_p_007627",
    language: "hi",
    content: "जलशीर्ष खोपड़ी के अंदर तरल पदार्थ का निर्माण है जिससे मस्तिष्क में सूजन होती है। जलशीर्ष का अर्थ है मस्तिष्क पर जल।",
  },
  {
    sourceQueryId: 592382,
    passageId: "hi_p_008811",
    language: "hi",
    content: "वेबएम.डी. के अनुसार, जिन स्थितियों के कारण पैर और टखने सूजते हैं, उनमें गर्भावस्था, पैर या टखने में चोट, लिम्फेडेमा और संक्रमण शामिल हैं। अन्य संभावित कारणों में हृदय, यकृत या गुर्दे की बीमारी; रक्त का थक्का; या शिरापरक अपर्याप्तता शामिल हैं।",
  },
  {
    sourceQueryId: 738720,
    passageId: "hi_p_010172",
    language: "hi",
    content: "त्वचाविज्ञान सर्जरी क्या है? त्वचाविज्ञान सर्जरी विभिन्न शल्य चिकित्सा विधियों द्वारा चिकित्सकीय रूप से आवश्यक और सौंदर्य संबंधी त्वचा, नाखून और बाल स्थितियों का उपचार है। इसे त्वचाविज्ञान सर्जरी भी कहा जाता है। त्वचाविज्ञानी सभी मूलभूत त्वचाविज्ञान सर्जरी में प्रशिक्षित होते हैं। कुछ त्वचाविज्ञानी उन्नत त्वचाविज्ञान सर्जरी प्रक्रियाओं में अतिरिक्त प्रशिक्षण प्राप्त करते हैं।",
  },
  {
    sourceQueryId: 433037,
    passageId: "hi_p_011539",
    language: "hi",
    content: "जेफ बेज़ोस की कुल संपत्ति और वेतन: जेफ बेज़ोस एक अमेरिकी परोपकारी, व्यवसायी और अंतरिक्ष अन्वेषक हैं जिनकी कुल संपत्ति 89 अरब डॉलर है। जेफ बेज़ोस अमेज़ॅन.कॉम के संस्थापक, मुख्य कार्यकारी अधिकारी, अध्यक्ष और बोर्ड के अध्यक्ष हैं।",
  },
  {
    sourceQueryId: 570416,
    passageId: "hi_p_012842",
    language: "hi",
    content: "कीटाणुनाशक उपचार आम तौर पर 2-3 दिनों के बीच चलता है और इसके लिए व्यापक तैयारी की आवश्यकता होती है। पूरे ढांचे को सील करना एक महत्वपूर्ण और विशिष्ट पहलू है जिससे संरचना में कीटाणुनाशक गैसें केंद्रित होती हैं और संरचना में मौजूद होती हैं।",
  },
  {
    sourceQueryId: 460404,
    passageId: "hi_p_014184",
    language: "hi",
    content: "एक पैनोरमिक रेडियोग्राफ में बाएं प्रीमोलर-मोलर क्षेत्र के क्षेत्र में एक स्पष्ट, कॉर्टिकेटेड, मल्टीलोकुलर रेडियोल्यूसेंट घाव दिखाया गया है। फोड़े सबएरोलर (23%), इंट्राममरी यूनिलोकुलर (12%), या इंट्राममरी मल्टीलोकुलर (65%) पर स्थित होते हैं।",
  },
  {
    sourceQueryId: 667552,
    passageId: "hi_p_015475",
    language: "hi",
    content: "एक विस्थापित घुटने का ढक्कन कैसे बनता है। जब घुटने का ढक्कन आंशिक रूप से अपनी स्थिति से बाहर निकल जाता है, तो डॉक्टर इस स्थिति को सबलक्सेशन कहते हैं। एक आंशिक रूप से विस्थापित घुटने का ढक्कन पिछले विस्थापन या घुटने के ढक्कन के बाहर की ओर खिसकने की विरासत में मिली प्रवृत्ति का परिणाम हो सकता है। घुटने के नीचे कोमलता और दर्द हो सकता है जब व्यक्ति घुटने को मोड़ता है या सीढ़ियाँ चढ़ता है। घुटने की अस्थिरता की भावना एक आम शिकायत है। \"एक विस्थापित घुटना (घुटने के ढक्कन के विपरीत) ठीक होने के मामले में सबसे चुनौतीपूर्ण खेल चोटों में से एक है,\" फ्लोरिडा के गल्फ ब्रीज़ में एंड्रयूज़ इंस्टीट्यूट के प्राथमिक देखभाल खेल चिकित्सा के निदेशक जोशुआ हैकेल, एमडी कहते हैं।",
  },
  {
    sourceQueryId: 454795,
    passageId: "hi_p_016867",
    language: "hi",
    content: "इसका मतलब है कि यदि दरवाजे की चौड़ाई 32 इंच है, तो आपके पास 32 इंच चौड़ा और 32 इंच लंबा साफ स्थान होना चाहिए जो शौचालय में जाता है। एक बार शौचालय के अंदर, आपको शौचालय, सिंक, टब या बिडेट के सामने कम से कम 21 इंच की जगह और शॉवर के सामने 24 इंच की साफ जगह की आवश्यकता होगी।",
  },
  {
    sourceQueryId: 1164551,
    passageId: "hi_p_018035",
    language: "hi",
    content: "डिस्कवरी चैनल डायरेक्टटीवी पर चैनल 278 है। रिमोट पर, मेनू पर जाएं, फिर शो खोजें, फिर डिस के साथ शुरू होने वाले चैनलों को खोज बॉक्स में डिस्प्ले किया जाएगा। आप जिस चैनल को चाहते हैं उसे चुनें और वहां आप हैं।",
  },
  {
    sourceQueryId: 628484,
    passageId: "hi_p_019430",
    language: "hi",
    content: "यदि आपके रियल्टर ने इन महत्वपूर्ण मुद्दों का उल्लेख नहीं किया है, तो आपको थोड़ा और खुद खुद खुद खुदाई करने की आवश्यकता है। #1. एओएओ शुल्क (उर्फ रखरखाव शुल्क या एचओए शुल्क)। हवाई में, हर कोंडोमिनियम विकास के लिए एओएओ (अपार्टमेंट मालिकों का संघ) होना आवश्यक है। यह संघ कोंडोमिनियम परिसर को चलाने और बनाए रखने के लिए जिम्मेदार कोंडोमिनियम मालिकों से बना है।",
  },
  {
    sourceQueryId: 485808,
    passageId: "hi_p_020732",
    language: "hi",
    content: "वास्तविकता यह है कि हमें अच्छे स्वास्थ्य के लिए स्वच्छ हवा की आवश्यकता होती है। जीवाश्म ईंधन हमारे स्वास्थ्य के लिए खराब होने का मुख्य कारण यह है कि उनका दहन करने से कई अत्यधिक हानिकारक गैसें जैसे कि कार्बन डाइऑक्साइड और मोनोऑक्साइड, सल्फर ऑक्साइड, नाइट्रोजन ऑक्साइड और हाइड्रोकार्बन उत्सर्जित होते हैं। वास्तव में, वायुमंडल में छोड़े गए कार्बन डाइऑक्साइड की मात्रा अब 150 साल पहले की तुलना में 25 प्रतिशत से अधिक है। जीवाश्म ईंधन वायुमंडल में नाइट्रस ऑक्साइड और मीथेन के स्तर में वृद्धि के लिए भी जिम्मेदार हैं।",
  },
  {
    sourceQueryId: 631612,
    passageId: "hi_p_021989",
    language: "hi",
    content: "एक अकाउंट एक्जीक्यूटिव क्या करता है? अकाउंट एक्जीक्यूटिव दो प्राथमिक कारणों से मौजूद हैं: वर्तमान ग्राहकों को खुश रखना, और नए ग्राहकों को आकर्षित करना। यदि आप कई जिम्मेदारियों को संभालना, विभिन्न प्रकार के व्यक्तित्व के साथ काम करना, और बिक्री करने की भीड़ को महसूस करना पसंद करते हैं, तो एक अकाउंट एक्जीक्यूटिव के रूप में जीवन आपके लिए उपयुक्त होगा। इसके अलावा, यह एक ऐसा पद है जो कई उद्योगों में देखा जाता है, इसलिए आपको अपने कौशल को प्रदर्शित करने का अवसर मिलता है।",
  },
  {
    sourceQueryId: 195419,
    passageId: "hi_p_023250",
    language: "hi",
    content: "हमारी वेबसाइट पर आने के लिए धन्यवाद। कैल्वर्ट काउंटी, एम.डी. के पास स्थित प्रिंस फ्रेडरिक का वाइनगार्डनर जी.एम.सी. ब्युक वॉशिंगटन, डी.सी. से कुछ ही मिनटों की दूरी पर है, जिससे हम आपके लिए एक प्रमुख नया और इस्तेमाल किया गया ब्युक जी.एम.सी. डीलर बन गए हैं। वाइनगार्डनर ने कैल्वर्ट काउंटी क्षेत्र को ब्युक और जी.एम.सी. द्वारा प्रदान की जाने वाली सर्वश्रेष्ठ सेवाओं के साथ सेवा दी है। हम अपने ग्राहकों के लिए विशेष प्रस्ताव और प्रोत्साहन प्रदान करते हैं।",
  },
  {
    sourceQueryId: 500878,
    passageId: "hi_p_024470",
    language: "hi",
    content: "सोयाला नाम का उच्चारण [सोया-या-ला, सोया-ला] के रूप में किया जाता है। सोयाला मूल अमेरिकी मूल से लिया गया है। इसका अर्थ है शीतकालीन संक्रांति के दौरान जन्मा। सोयाला, सोयालिया, सोयालिया, सोयाला, और सोयाल्या सोयाला के पर्यायी लिप्यंतरण हैं। संबंधित श्रेणी अमेरिकन भी देखें। सोयाला एक बच्ची के नाम के रूप में दुर्लभ है। यह शीर्ष 1000 शिशु नामों में सूचीबद्ध नहीं है। सोयाला जैसे ध्वनि वाले शिशु नामों में सैसिलिया, साहेला, साहीला, साहीला, सहेला, साहेले, साहिला, साहिला, सैलिया, सलासिया, सलासिया, सलसिया, सलिया, सलिया, सलिहा, और सलीका शामिल हैं।",
  },
  {
    sourceQueryId: 670568,
    passageId: "hi_p_025798",
    language: "hi",
    content: "फोरेंसिक मनोविज्ञान की नौकरियों के लिए आपको जिन कौशलों की आवश्यकता होती है, उनमें मजबूत अनुसंधान क्षमता, महत्वपूर्ण सोच कौशल, कानूनी प्रणाली का अच्छा ज्ञान और ठोस बोले गए और लिखित संचार कौशल शामिल हैं। इस शोध के विशिष्ट विषय में रोजगार कानून, बीमा दावा कानून और पारिवारिक कानून शामिल हो सकते हैं। ठोस और कुशल अनुसंधान कौशल आमतौर पर पहले भर्ती निर्णय कारकों में से एक होता है जिस पर संभावित नियोक्ता तब विचार करते हैं जब आप अपनी पहली कुछ फोरेंसिक मनोविज्ञान की नौकरियों के लिए आवेदन करते हैं।",
  },
  {
    sourceQueryId: 287004,
    passageId: "hi_p_027000",
    language: "hi",
    content: "संयुक्त राज्य अमेरिका में कभी नहीं दिखाए गए एक टीवी विज्ञापन में, एडी मर्फी ने टोयोटा सेडान के सामने के बम्पर को चूमा। उनके आठ बच्चे हैं। उनका पहला और सबसे बड़ा बच्चा पॉलेट मैकनीली से था: बेटा, एरिक (10 जुलाई 1989 को जन्मा)।",
  },
  {
    sourceQueryId: 1185653,
    passageId: "hi_p_028212",
    language: "hi",
    content: "ए: हीलियम गुब्बारे तैरते हैं क्योंकि वे आसपास की हवा की तुलना में कम घने होते हैं, जिससे वे ऊपर उठते हैं। गुरुत्वाकर्षण हीलियम गुब्बारों पर उसी तरह काम करता है जैसे यह आसपास की हवा पर करता है; इससे इससे कोई फर्क नहीं पड़ता कि गुब्बारा तैरता है या नहीं। यह सब सापेक्ष घनत्व पर निर्भर करता है। आगे पढ़ते रहें।",
  },
  {
    sourceQueryId: 559641,
    passageId: "hi_p_029491",
    language: "hi",
    content: "ऑस्ट्रेलिया, जमैका और न्यू ऑरलियन्स में, हरे प्याज को शैलट्स कहा जाता है। और, हर जगह, कई लोगों के लिए हरे प्याज या तो यंग लीक्स, प्याज के शीर्ष, या शैलट्स के तने होते हैं। ऑस्ट्रेलिया, जमैका और न्यू ऑरलियन्स में, हरे प्याज को शैलट्स कहा जाता है। और, हर जगह, कई लोगों के लिए हरे प्याज या तो यंग लीक्स, प्याज के शीर्ष, या शैलट्स के तने होते हैं।",
  },
  {
    sourceQueryId: 612319,
    passageId: "hi_p_030923",
    language: "hi",
    content: "सांता क्लारा काउंटी सैन जोस-सनीवेल-सांता क्लारा, सी.ए. महानगरीय सांख्यिकीय क्षेत्र के साथ-साथ सैन जोस-सैन फ्रांसिस्को-ओकलैंड, सी.ए. संयुक्त सांख्यिकीय क्षेत्र में शामिल है।",
  },
  {
    sourceQueryId: 633259,
    passageId: "hi_p_032196",
    language: "hi",
    content: "यह कॉक्ससैकी हो सकता है: हथेलियों और तलवों पर छोटे लाल छाले होने के कई कारण हो सकते हैं। आम तौर पर एक वायरल संक्रमण (कॉक्ससैकी वायरस) हाथ-पैर-मुँह रोग का कारण बनता है। उपचार लक्षणों के लिए होता है। अपने डॉक्टर से मिलें क्योंकि अन्य कारण भी हैं जिन्हें एंटीबायोटिक्स की आवश्यकता होती है। ...और अधिक पढ़ें।",
  },
  {
    sourceQueryId: 671397,
    passageId: "hi_p_033548",
    language: "hi",
    content: "कौन सा उपकरण आर्द्रता को मापता है? आर्द्रता को मापने वाले उपकरण को हाइग्रोमीटर कहा जाता है। हाइग्रोमीटर एक ऐसा उपकरण है जो हवा में सापेक्ष आर्द्रता को मापता है। हाइग्रोमीटर का एक सामान्य प्रकार है मनोविज्ञानी, एक ऐसा उपकरण जो एक गीले बल्ब और एक सूखे बल्ब के तापमान को एक साथ मापता है।",
  },
  {
    sourceQueryId: 643494,
    passageId: "hi_p_034853",
    language: "hi",
    content: "1. कम करने वाली परिस्थिति - (कानून) एक परिस्थिति जो किसी व्यक्ति को बरी नहीं करती है, लेकिन जिससे अपराध से जुड़ी सजा कम हो जाती है। विचार, परिस्थिति, स्थिति - जानकारी जिसे निर्णय लेते समय ध्यान में रखी जानी चाहिए; एक अन्य विचार वह समय है जो इसमें लगेगा।",
  },
  {
    sourceQueryId: 202260,
    passageId: "hi_p_036007",
    language: "hi",
    content: "आउटफील्डर टाई कॉब, जिनका करियर 1928 में समाप्त हुआ, मेजर लीग बेसबॉल (एम.एल.बी.) के इतिहास में सबसे अधिक बल्लेबाजी औसत रखते हैं। उन्होंने 24 सत्रों में ज्यादातर डेट्रॉइट टाइगर्स के लिए .366 की औसत से बल्लेबाजी की। इसके अलावा, उन्होंने पूरे सत्र में अमेरिकन लीग में बी.ए. में अग्रणी होने के लिए रिकॉर्ड 11 बल्लेबाजी खिताब जीते।",
  },
  {
    sourceQueryId: 527792,
    passageId: "hi_p_037125",
    language: "hi",
    content: "इतालवी लोग अपने भोजन को बहुत गंभीरता से लेते हैं। इस प्रकार उनके व्यंजनों में लगाए गए सभी कामों का कारण है। इतालवी कई ऐसी चीजें खाते हैं जो आम तौर पर यू.के. में नहीं खाई जाती हैं, जैसे घोंघे, घोड़ा, गधा, साही, बकरी, गिनी सुअर, खरगोश, जंगली सूअर, समुद्री अर्चिन, समुद्री घोंघे, ऑक्टोपस, स्क्विड, चिड़िया, मोर आदि। इतालवी लोग सिर्फ दूधिया कॉफी पीते हैं, जैसे कि कैप्पुचिनो और कैफेलेट, नाश्ते में सबसे पहले।",
  },
  {
    sourceQueryId: 202822,
    passageId: "hi_p_038357",
    language: "hi",
    content: "सर्वोच्च न्यायालय के न्यायाधीश: सर्वोच्च न्यायालय देश का सर्वोच्च न्यायालय है। इसमें एक मुख्य न्यायाधीश या प्रमुख न्यायाधीश और आठ सहायक न्यायाधीश होते हैं। न्यायाधीशों की नियुक्ति राष्ट्रपति द्वारा की जाती है और सीनेट के मत से अनुमोदित की जाती है। न्यायाधीश आजीवन सेवा करते हैं जब तक कि वे सेवानिवृत्त नहीं हो जाते। उनका काम कांग्रेस द्वारा पारित कानूनों की व्याख्या करना है। हमारी सरकार की स्थापना के बाद से, एक सौ से अधिक न्यायाधीशों ने न्यायालय में सेवा की है, और हाल तक, सभी पुरुष थे। सैंड्रा डे ओ'कॉनर सर्वोच्च न्यायालय में नामित होने वाली पहली महिला थीं। उन्हें 1981 में नियुक्त किया गया था।",
  },
  {
    sourceQueryId: 127220,
    passageId: "hi_p_039530",
    language: "hi",
    content: "सामाजिक परिस्थितियाँ। सामाजिक परिस्थितियों की परिभाषा: अवधारणाओं का एक समूह जो किसी व्यक्ति के सामाजिक वातावरण से जुड़े मानदंडों या गतिविधियों से परिणामित होता है या प्रभावित होता है। (एन.सी.आई.) अवधारणाओं का एक समूह जो किसी व्यक्ति के सामाजिक वातावरण से जुड़े मानदंडों या गतिविधियों से परिणामित होता है या प्रभावित होता है। सामाजिक परिस्थितियाँ अवधारणात्मक संस्थाओं के समूह का हिस्सा हैं।",
  },
  {
    sourceQueryId: 494735,
    passageId: "hi_p_040703",
    language: "hi",
    content: "अर्धचालक भौतिकी की जानकारी के लिए, अर्धचालक देखें। अर्धचालक उपकरण इलेक्ट्रॉनिक घटक हैं जो अर्धचालक सामग्री, मुख्य रूप से सिलिकॉन, जर्मेनियम और गैलियम आर्सेनाइड, के इलेक्ट्रॉनिक गुणों का उपयोग करते हैं, साथ ही कार्बनिक अर्धचालक भी। अर्धचालक उपकरणों ने अधिकांश अनुप्रयोगों में थर्मियॉनिक उपकरणों (वैक्यूम ट्यूब) को प्रतिस्थापित कर दिया है। अर्धचालक डायोड एक उपकरण है जो आमतौर पर एक एकल पी-एन जंक्शन से बनाया जाता है। पी-प्रकार और एन-प्रकार अर्धचालक के जंक्शन पर एक अपक्षय क्षेत्र बनता है जहां मोबाइल चार्ज वाहकों की कमी से विद्युत प्रवाह बाधित होता है।",
  },
  {
    sourceQueryId: 285514,
    passageId: "hi_p_041930",
    language: "hi",
    content: "जॉनी डेप कैसल होम्स: जॉनी डेप एक सफल घर मालिक हैं। उनके पास छह घर हैं जिनकी कीमत 23 लाख डॉलर से 1.6 करोड़ डॉलर तक है। कैलिफोर्निया में उनके पास चार घर हैं, जिनमें से एक 1927 का परी कथा-सदृश महल है।",
  },
  {
    sourceQueryId: 529333,
    passageId: "hi_p_043275",
    language: "hi",
    content: "आज बाजार में दो प्रकार के पोर्टेबल ऑक्सीजन सांद्रक उपलब्ध हैं: निरंतर प्रवाह ऑक्सीजन सांद्रक और स्पंदित खुराक, या आंतरायिक प्रवाह, ऑक्सीजन सांद्रक। इन दोन प्रकार की ऑक्सीजन प्रणालियों के बहुत अलग लाभ और सीमाएँ हैं और प्रत्येक एक विशिष्ट प्रकार के रोगी के लिए सबसे उपयुक्त है।",
  },
  {
    sourceQueryId: 655414,
    passageId: "hi_p_044586",
    language: "hi",
    content: "हार्वर्ड में औसत जी.पी.ए. 4.04 है। (अधिकांश स्कूल 4.0 में से एक भारित जी.पी.ए. का उपयोग करते हैं, हालांकि कुछ एक भारित जी.पी.ए. नहीं दिखाते हैं। 4.04 के जी.पी.ए. के साथ, हार्वर्ड को आपको अपनी कक्षा में शीर्ष पर रहने की आवश्यकता है। आपको अन्य आवेदकों के साथ प्रतिस्पर्धा करने के लिए अपनी सभी कक्षाओं में लगभग सीधे ए की आवश्यकता होगी। इसके अलावा, आपको कठिन कक्षाएं - ए.पी. या आई.बी. पाठ्यक्रम - लेनी चाहिए ताकि यह दिखाया जा सके कि कॉलेज-स्तरीय शिक्षा आसान है।",
  },
  {
    sourceQueryId: 719751,
    passageId: "hi_p_045739",
    language: "hi",
    content: "हाथ से हाथ मिलाकर लड़ाई (हाथ से हाथ मिलाकर लड़ाई से संबंधित) हाथ से हाथ मिलाकर लड़ाई (कभी-कभी संक्षेप में एच.टी.एच. या एच2एच के रूप में जाना जाता है) दो या दो से अधिक व्यक्तियों के बीच बहुत कम दूरी (कुश्ती की दूरी) पर घातक या गैर-घातक शारीरिक टकराव है जिसमें आग्नेयास्त्रों या अन्य दूरी हथियारों का उपयोग शामिल नहीं है।",
  },
  {
    sourceQueryId: 434794,
    passageId: "hi_p_046905",
    language: "hi",
    content: "जून 2018 में कोडियाक में मौसम। जून में कोडियाक में औसतन 9 घंटे की धूप के साथ 13 डिग्री सेल्सियस दिन के अधिकतम तापमान की अपेक्षा करें। 2018 में अलास्का में अपनी अगली छुट्टी बुक करने से पहले जून में कोडियाक के लिए अधिक दीर्घकालिक मौसम औसत की जांच करें।",
  },
  {
    sourceQueryId: 6206,
    passageId: "hi_p_048147",
    language: "hi",
    content: "अवायवीय और वायुजीवीय श्वसन दोनों में पहला चरण ग्लाइकोलाइसिस कहलाता है। यह एक ग्लूकोज (चीनी) अणु लेने और इसे पाइरुवेट और ऊर्जा (2 ए.टी.पी.) में तोड़ने की प्रक्रिया है। हम वायुजीवीय श्वसन के दौरान इसकी गहराई से चर्चा करेंगे। अवायवीय श्वसन में दूसरा चरण किण्वन कहलाता है। किण्वन पाइरुवेट (ग्लाइकोलाइसिस का अंतिम उत्पाद) से शुरू होता है। ग्लाइकोलाइसिस कोशिका के साइटोसोल में होता है। साइटोसोल में हम 1 ग्लूकोज अणु को 2 पाइरुवेट अणुओं में परिवर्तित करते हैं।",
  },
  {
    sourceQueryId: 1164236,
    passageId: "hi_p_049494",
    language: "hi",
    content: "परिधीय तंत्रिकाओं में संयोजी ऊतक की तीन परतें होती हैं: एपिन्यूरियम - संयोजी ऊतक की बाहरी परत है जो दृढ़तानिका के साथ निरंतर होती है। इसमें तंत्रिका के भीतर किसी भी फैसिकल (गुच्छे) के बीच में संयोजी ऊतक भी शामिल है। पेरिन्यूरियम - संयोजी ऊतक का आवरण है जो अक्षतंतुओं के फैसिकल को घेरता है। एंडोन्यूरियम - व्यक्तिगत अक्षतंतुओं को घेरने वाले सूक्ष्म संयोजी ऊतक तंतु हैं।",
  },
  {
    sourceQueryId: 1185869,
    passageId: "en_p_000000",
    language: "en",
    content: "The presence of communication amid scientific minds was equally important to the success of the Manhattan Project as scientific intellect was. The only cloud hanging over the impressive achievement of the atomic researchers and engineers is what their success truly meant; hundreds of thousands of innocent lives obliterated.",
  },
  {
    sourceQueryId: 669148,
    passageId: "en_p_001281",
    language: "en",
    content: "Regarded as the world authority on magical creatures, Newt Scamander is the author of Fantastic Beasts and Where to Find Them, which has been an approved textbook at Hogwarts since its publication in 1927 and can be found in most wizarding households..",
  },
  {
    sourceQueryId: 1164695,
    passageId: "en_p_002563",
    language: "en",
    content: "There are several different reasons why the prostate may become enlarged. 1 Causes of an enlarged prostate may include: 2 Benign prostatic hyperplasia (BPH) 3 Prostate cancer. 4 Prostatitis.",
  },
  {
    sourceQueryId: 1173733,
    passageId: "en_p_003912",
    language: "en",
    content: "Boughs definition, a branch of a tree, especially one of the larger or main branches. See more.",
  },
  {
    sourceQueryId: 720466,
    passageId: "en_p_004974",
    language: "en",
    content: "What is Astronomy? Astronomy is the study of the universe, namely the objects we. observe, like the Moon, Sun, and planets in our Solar System; stars; our Milky Way Galaxy, and other galaxies; and, a host of. other celestial objects and phenomena, like nebulae, and black. holes! Hubble Space Telescope Images.",
  },
  {
    sourceQueryId: 243321,
    passageId: "en_p_006220",
    language: "en",
    content: "Early Car Lease Termination. You decided to lease a car. Then, a year or two into your lease agreement, something changes. You need to get out of your lease early. The truth is, anyone can break their lease at any time—you just need to know the consequences. If you take the right steps, you can end your lease early and avoid costly penalties.",
  },
  {
    sourceQueryId: 756426,
    passageId: "en_p_007634",
    language: "en",
    content: "Hydrocephalus is a buildup of fluid inside the skull that leads to brain swelling. Hydrocephalus means water on the brain.",
  },
  {
    sourceQueryId: 592382,
    passageId: "en_p_008819",
    language: "en",
    content: "Conditions that cause swollen feet and ankles include pregnancy, a foot or ankle injury, lymphedema and infections, explains WebMD. Other possible causes include heart, liver or kidney disease; a blood clot; or venous insufficiency.",
  },
  {
    sourceQueryId: 738720,
    passageId: "en_p_010177",
    language: "en",
    content: "What is dermatologic surgery? Dermatologic surgery is the treatment of medically necessary and cosmetic skin, nail, and hair conditions by various surgical methods. It is also called dermatological surgery. Dermatologists are all trained in basic dermatologic surgery. Some dermatologists undergo additional training in advanced dermatologic surgery procedures.",
  },
  {
    sourceQueryId: 433037,
    passageId: "en_p_011546",
    language: "en",
    content: "Jeff Bezos net worth and salary: Jeff Bezos is an American philanthropist, businessman and space explorer who has a net worth of $89 billion. Jeff Bezos is the founder, chief executive officer, president and chairman of the board of Amazon.com.",
  },
  {
    sourceQueryId: 570416,
    passageId: "en_p_012850",
    language: "en",
    content: "Termite fumigation treatment generally lasts between 2-3 days and requires extensive preparation.An important and distinctive aspect of whole structure termite fumigation is the sealing of the entire structure to be treated within a tent which concentrates and contains the termiticidal gases in the structure.",
  },
  {
    sourceQueryId: 460404,
    passageId: "en_p_014193",
    language: "en",
    content: "A panoramic radiograph showed a well defined, corticated, multilocular radiolucent lesion in the region of the left premolar-molar region. Abscesses are located subareolar (23%), intramammary unilocular (12%), or intramammary multilocular (65%).",
  },
  {
    sourceQueryId: 667552,
    passageId: "en_p_015482",
    language: "en",
    content: "How a Dislocated Kneecap Happens. When the kneecap partially moves out of its position, doctors call the condition a subluxation. A partially dislocated kneecap can be the result of a previous dislocation or an inherited tendency for the kneecap to slide to the outside.There could be tenderness under the kneecap and pain when the person twists the knee or climbs stairs. A feeling of the knee’s instability is a common complaint.islocated Knee Versus Dislocated Kneecap. “A dislocated knee (as opposed to a kneecap) is one of the most challenging sports injuries in terms of recovery,” says Joshua Hackel, MD, the director of Primary Care Sports Medicine at the Andrews Institute in Gulf Breeze, Florida.",
  },
  {
    sourceQueryId: 454795,
    passageId: "en_p_016875",
    language: "en",
    content: "This means that if the door width is 32 inches, you must have a passage of 32 inches wide and 32 inches long of clear space leading into the bathroom. Once inside the bathroom, you will need a minimum of 21 inches of space in front of the toilet, sink, tub or bidet and 24 inches of clear space in front of a shower.",
  },
  {
    sourceQueryId: 1164551,
    passageId: "en_p_018041",
    language: "en",
    content: "The Discovery channel is channel 278 on DirecTV. On the remote, go to the menu, then Search for Shows, then in the search box on the left spell out DIS and the channels that start with DIS will be displayed. Select the one you want and there you are.",
  },
  {
    sourceQueryId: 628484,
    passageId: "en_p_019436",
    language: "en",
    content: "If your realtor hasn’t mentioned these important issues, you need to dig a little deeper on your own. #1. AOAO fees (aka maintenance fees or HOA fees). In Hawaii, every condominium development is required to have an AOAO (Association of Apartment Owners).The association is comprised of the condo owners who are responsible for running and maintaining the condominium complex.n Hawaii, every condominium development is required to have an AOAO (Association of Apartment Owners). The association is comprised of the condo owners who are responsible for running and maintaining the condominium complex.",
  },
  {
    sourceQueryId: 485808,
    passageId: "en_p_020737",
    language: "en",
    content: "The fact is that we need clean air for good health. The main reason why fossil fuels are bad for our health is because burning them releases a number of extremely harmful gases, such as carbon dioxide and monoxide, sulfur oxides, nitrogen oxides, and hydrocarbons.his is the gas that is emitted the most when fossil fuels are burned. In fact, the amount of carbon dioxide released into the atmosphere is now over 25 percent more than it was 150 years ago. Fossil fuels are also responsible for the increase in nitrous oxide and methane levels in the atmosphere.",
  },
  {
    sourceQueryId: 631612,
    passageId: "en_p_021992",
    language: "en",
    content: "What does an Account Executive do? Account executives exist for two primary reasons: to keep current customers happy, and to attract new customers. If you like juggling multiple responsibilities, working with a variety of personality types, and feeling the rush of making a sale, then life as an account executive will suit you well. Plus, this is a position that is seen in many industries, so you have the opportunity to take your skill set...",
  },
  {
    sourceQueryId: 195419,
    passageId: "en_p_023254",
    language: "en",
    content: "Thank you for visiting our website. Winegardner GMC Buick of Prince Frederick, situated near Calvert County, MD is only a few minutes from Washington, D.C making us your leading new and used Buick GMC dealer. Winegardner has served the Calvert County area with the best that Buick and GMC have to offer. We offer specials and incentives for our customers.",
  },
  {
    sourceQueryId: 500878,
    passageId: "en_p_024474",
    language: "en",
    content: "[ syll. so-ya-la, soy-ala] The baby girl name Soyala is pronounced as S-OY AA LAH †. Soyala is derived from Native American origins. The name means born during the winter solstice. Soyalah, Soyalia, Soyaliya, Soyalla, and Soyalya are variant transcriptions of Soyala. See also the related category american. Soyala is rare as a baby girl name. It is not listed in the top 1000. Baby names that sound like Soyala include Sacilia, Saheala, Saheela, Saheila, Sahela, Saheleigh, Sahilah, Sahilla, Sahyla, Sahylla, Sailia, Salacia, Salaciah, Salcia, Salea, Saleah, Salia, Saliah, Saliha, and Salika.",
  },
  {
    sourceQueryId: 670568,
    passageId: "en_p_025802",
    language: "en",
    content: "Skills that you need for forensic psychology jobs include strong research abilities, critical thinking skills, a good working knowledge of the legal system, and solid spoken and written communication skills.he specific subject matter of this research can include employment law, insurance claim law, and family law just to name a few. Solid and efficient research skills are typically one of the first hiring decision factors that potential employers consider when you apply for some of your first forensic psychology jobs.",
  },
  {
    sourceQueryId: 287004,
    passageId: "en_p_027006",
    language: "en",
    content: "In a TV commercial never shown in the United States, Eddie Murphy kissed the front bumper of a Toyota sedan. He has eight children. His first and oldest child was with Paulette McNeely: son, Eric (born on 10 July 1989).",
  },
  {
    sourceQueryId: 1185653,
    passageId: "en_p_028218",
    language: "en",
    content: "A: Helium balloons float because they are less dense than the surrounding air, which causes them to rise. Gravity acts on helium balloons the same way it does on the surrounding air; it has no effect on whether the balloon floats or not. It all comes down to relative densities. Continue Reading",
  },
  {
    sourceQueryId: 559641,
    passageId: "en_p_029496",
    language: "en",
    content: "In Australia, Jamaica, and in New Orleans, Green Onions are called shallots. And, all over the place, to many people Green Onions are either young leeks, the tops of onions, or the stems of shallots.n Australia, Jamaica, and in New Orleans, Green Onions are called shallots. And, all over the place, to many people Green Onions are either young leeks, the tops of onions, or the stems of shallots.",
  },
  {
    sourceQueryId: 612319,
    passageId: "en_p_030928",
    language: "en",
    content: "Santa Clara County is included in the San Jose-Sunnyvale-Santa Clara, CA Metropolitan Statistical Area as well as the San Jose-San Francisco-Oakland, CA Combined Statistical Area.",
  },
  {
    sourceQueryId: 633259,
    passageId: "en_p_032204",
    language: "en",
    content: "Could be coxsackie: Small red blisters on palms & soles can have several causes. Commonly a viral infection (coxsackie virus) causes hand-foot-mouth disease. Treatment is for symptoms. See your doctor since there are other causes which need antiboitics. ...Read more.",
  },
  {
    sourceQueryId: 671397,
    passageId: "en_p_033555",
    language: "en",
    content: "What instrument measures humidity? The instrument that measures humidityis called a hygrometer.. A hygrometer is an instrument thatmeasures relative humidity in the air. One common kind ofhygrometer is a psych…rometer, a device that measures thetemperature of a wet bulb and a dry bulb simultaneously.",
  },
  {
    sourceQueryId: 643494,
    passageId: "en_p_034859",
    language: "en",
    content: "1. mitigating circumstance - (law) a circumstance that does not exonerate a person but which reduces the penalty associated with the offense. consideration, circumstance, condition-information that should be kept in mind when making a decision; another consideration is the time it would take.",
  },
  {
    sourceQueryId: 202260,
    passageId: "en_p_036012",
    language: "en",
    content: "Outfielder Ty Cobb, whose career ended in 1928, has the highest batting average in Major League Baseball (MLB) history. He batted .366 over 24 seasons, mostly with the Detroit Tigers. In addition, he won a record 11 batting titles for leading the American League in BA over the course of an entire season.",
  },
  {
    sourceQueryId: 527792,
    passageId: "en_p_037130",
    language: "en",
    content: ". Italians take their food very seriously. Thus the reason for all the work that is put into their cuisines.. Italians eat many things that are not usually eaten in the UK, for example, snails, horse, donkey, hedgehog, goat, guinea pig, rabbit, wild boar, sea urchin, sea snails, octopus, squid, sparrows, peacock etc. . Italians only drink milky coffee, like cappuccino and caffelatte, first thing in the morning for breakfast.",
  },
  {
    sourceQueryId: 202822,
    passageId: "en_p_038361",
    language: "en",
    content: "The Supreme Court Justices. The Supreme Court is the highest court in the land. It has a chief justice, or head judge, and eight associate justices. The justices are appointed by the president and approved by a vote of the Senate. The justices serve for life unless they choose to retire. Their job is to interpret laws passed by Congress. Since our government was established, more than one hundred justices have served on the Court, and until recently, all were men. Sandra Day O’Connor was the first woman named to the Supreme Court. She was appointed in 1981.",
  },
  {
    sourceQueryId: 127220,
    passageId: "en_p_039535",
    language: "en",
    content: "Social Circumstances. Definition of Social Circumstances: A set of concepts that results from or is influenced by criteria or activities associated with the social environment of a person. (NCI) A set of concepts that results from or is influenced by criteria or activities associated with the social environment of a person. Social Circumstances is part of the Conceptual Entities group.",
  },
  {
    sourceQueryId: 494735,
    passageId: "en_p_040705",
    language: "en",
    content: "For information on semiconductor physics, see semiconductor. Semiconductor devices are electronic components that exploit the electronic properties of semiconductor materials, principally silicon, germanium, and gallium arsenide, as well as organic semiconductors.Semiconductor devices have replaced thermionic devices (vacuum tubes) in most applications. semiconductor diode is a device typically made from a single p–n junction. At the junction of a p-type and an n-type semiconductor there forms a depletion region where current conduction is inhibited by the lack of mobile charge carriers.",
  },
  {
    sourceQueryId: 285514,
    passageId: "en_p_041932",
    language: "en",
    content: "Johnny Depp Castle Homes. Johnny Depp is prolific home owner. He owns six homes which range from $2.3 to $16 million. He owns four homes in California, throughout Los Angeles and West Hollywood – one of which is a 1927 fairytale-like castle.",
  },
  {
    sourceQueryId: 529333,
    passageId: "en_p_043277",
    language: "en",
    content: "There are two types of portable oxygen concentrators available on the market today: Continuous flow oxygen concentrators and pulse dose, or intermittent flow, oxygen concentrators. These two types of oxygen systems have very different benefits and limitations and each is best suited for a specific type of patient.",
  },
  {
    sourceQueryId: 655414,
    passageId: "en_p_044588",
    language: "en",
    content: "The average GPA at Harvard is 4.04. (Most schools use a weighted GPA out of 4.0, though some report an unweighted GPA. With a GPA of 4.04, Harvard requires you to be at the top of your class. You'll need nearly straight A's in all your classes to compete with other applicants. Furthermore, you should be taking hard classes - AP or IB courses - to show that college-level academics is a breeze.",
  },
  {
    sourceQueryId: 719751,
    passageId: "en_p_045740",
    language: "en",
    content: "Hand-to-hand combat. (Redirected from Hand to hand combat) Hand-to-hand combat (sometimes abbreviated as HTH or H2H) is a lethal or non-lethal physical confrontation between two or more persons at very short range (grappling distance) that does not involve the use of firearms or other distance weapons.",
  },
  {
    sourceQueryId: 434794,
    passageId: "en_p_046905",
    language: "en",
    content: "Weather in Kodiak in June 2018. Expect 13°C daytime maximum temperatures in the shade with on average 9 hours of sunshine per day in Kodiak in June. Check more long-term weather averages for Kodiak in June before you book your next holiday to Alaska in 2018.",
  },
  {
    sourceQueryId: 6206,
    passageId: "en_p_048144",
    language: "en",
    content: "The first step in both anaerobic and aerobic respiration is called glycolysis. This is the process of taking one glucose (sugar) molecule and breaking it down into pyruvate and energy (2 ATP). We will discuss this in depth during aerobic respiration.The second step in anaerobic respiration is called fermentation. Fermentation starts with pyruvate (the end product of glycolysis).lycolysis is the first step in cellular respiration for both anaerobic and aerobic processes. Glycolysis takes place in the cytosol of a cell. In the cytosol we convert 1 molecule of glucose into 2 molecules of pyruvate.",
  },
  {
    sourceQueryId: 1164236,
    passageId: "en_p_049492",
    language: "en",
    content: "Peripheral nerves have three layers of connective tissue: Epineurium – is the outermost layer of connective tissue that is continuous with the dura mater. It also includes the connective tissue in between any fascicles (bundles) within the nerve. Perineurium – is the connective tissue sheath that surrounds a fascicle of axons. Endoneurium – is the delicate connective tissue fibers that surround individual axons. Subspecialty",
  },
  {
    sourceQueryId: 1185869,
    passageId: "mr_p_000000",
    language: "mr",
    content: "मॅनहॅटन प्रकल्पाच्या यशासाठी वैज्ञानिक बुद्धिमत्तेप्रमाणेच संप्रेषणाची उपस्थितीही तितकीच महत्त्वाची होती. अणुसंशोधक आणि अभियंत्यांच्या प्रभावी कामगिरीवर फक्त एकच ढग आहे ज्याचा त्यांच्या यशाचा खरा अर्थ होता; लाखो निर्दोष लोकांचे जीवन नष्ट झाले.",
  },
  {
    sourceQueryId: 669148,
    passageId: "mr_p_001280",
    language: "mr",
    content: "जादुई प्राण्यांवरील जागतिक अधिकार मानला जाणारा, न्यूट स्कॅमँडर हा फँटॅस्टिक बीस्ट्स अँड व्हेअर टू फाइंड थेमचा लेखक आहे, जो १९२७ मध्ये प्रकाशित झाल्यापासून हॉगवर्ट्समध्ये मान्यताप्राप्त पाठ्यपुस्तक आहे आणि बहुतेक जादूगार घरांमध्ये सापडते.",
  },
  {
    sourceQueryId: 1164695,
    passageId: "mr_p_002561",
    language: "mr",
    content: "प्रोस्टेट ग्रंथी का वाढू शकतो याची अनेक विविध कारणे आहेत. १. प्रोस्टेट ग्रंथी वाढण्याची कारणे समाविष्ट आहेत: २. सौम्य प्रोस्टेटिक हायपरप्लासिया (BPH) ३. प्रोस्टेट कॅन्सर ४. प्रोस्टेटाइटिस.",
  },
  {
    sourceQueryId: 1173733,
    passageId: "mr_p_003911",
    language: "mr",
    content: "बोग्स व्याख्या, झाडाची एक शाखा, विशेषत: मोठ्या किंवा मुख्य शाखांपैकी एक. अधिक पहा.",
  },
  {
    sourceQueryId: 720466,
    passageId: "mr_p_004973",
    language: "mr",
    content: "खगोलशास्त्र म्हणजे काय? खगोलशास्त्र म्हणजे विश्वाचा अभ्यास, म्हणजेच आपल्या सौरमालेतील चंद्र, सूर्य आणि ग्रह, तारे, आपली आकाशगंगा आणि इतर आकाशगंगा; आणि इतर अनेक खगोलीय वस्तू आणि घटना, जसे की नीहारिका, आणि कृष्णविवरे! हबल स्पेस टेलिस्कोप इमेजेस.",
  },
  {
    sourceQueryId: 243321,
    passageId: "mr_p_006219",
    language: "mr",
    content: "कार भाडेतत्त्वावर घेण्याची मुदत संपणे. तुम्ही कार भाडेतत्त्वावर घेण्याचा निर्णय घेतला. त्यानंतर, तुमच्या भाडेतत्त्व करारात एक किंवा दोन वर्षांनंतर, काहीतरी बदल होतो. तुम्हाला तुमच्या भाडेतत्त्वातून लवकर बाहेर पडावे लागेल. खरे तर, कोणीही कधीही त्यांचे भाडेतत्त्व मोडू शकतात - तुम्हाला फक्त परिणामांची माहिती असणे आवश्यक आहे. जर तुम्ही योग्य पावले उचलली, तर तुम्ही तुमचे भाडेतत्त्व लवकर संपवू शकता आणि महागड्या दंड टाळू शकता.",
  },
  {
    sourceQueryId: 756426,
    passageId: "mr_p_007636",
    language: "mr",
    content: "हायड्रोसेफॅलस म्हणजे कवटीच्या आत द्रव जमा होणे ज्यामुळे मेंदूला सूज येते. हायड्रोसेफॅलस म्हणजे मेंदूवर पाणी.",
  },
  {
    sourceQueryId: 592382,
    passageId: "mr_p_008820",
    language: "mr",
    content: "सुजलेले पाय आणि गुडघे यांना कारणीभूत ठरणाऱ्या परिस्थितींमध्ये गर्भधारणा, पाय किंवा घोट्याला दुखापत, लिम्फेडेमा आणि संसर्ग यांचा समावेश होतो. हे वेबएमडी स्पष्ट करते. इतर संभाव्य कारणांमध्ये हृदय, यकृत किंवा मूत्रपिंडाचा आजार; रक्त गोठणे; किंवा शिरांमधील अपुरेपणा यांचा समावेश होतो.",
  },
  {
    sourceQueryId: 738720,
    passageId: "mr_p_010177",
    language: "mr",
    content: "त्वचारोगशास्त्रीय शस्त्रक्रिया म्हणजे वैद्यकीयदृष्ट्या आवश्यक आणि सौंदर्यवर्धक त्वचा, नखे आणि केसांच्या स्थितींवर विविध शस्त्रक्रिया पद्धतींद्वारे केलेले उपचार. याला त्वचारोगशास्त्रीय शस्त्रक्रिया असेही म्हणतात. त्वचारोगतज्ञ सर्व मूलभूत त्वचारोगशास्त्रीय शस्त्रक्रियेत प्रशिक्षित असतात. काही त्वचारोगतज्ञ प्रगत त्वचारोगशास्त्रीय शस्त्रक्रिया प्रक्रियांमध्ये अतिरिक्त प्रशिक्षण घेतात.",
  },
  {
    sourceQueryId: 433037,
    passageId: "mr_p_011547",
    language: "mr",
    content: "जेफ बेझोसची निव्वळ संपत्ती आणि वेतन: जेफ बेझोस हे एक अमेरिकन परोपकारी, व्यवसायी आणि अंतराळ संशोधक आहेत, ज्यांची निव्वळ संपत्ती $८९ अब्ज आहे. जेफ बेझोस हे Amazon.com चे संस्थापक, मुख्य कार्यकारी अधिकारी, अध्यक्ष आणि मंडळाचे अध्यक्ष आहेत.",
  },
  {
    sourceQueryId: 570416,
    passageId: "mr_p_012850",
    language: "mr",
    content: "उर्वरित उपचार साधारणपणे २-३ दिवस टिकतो आणि त्यासाठी व्यापक तयारी करणे आवश्यक असते, जे संपूर्ण संरचनेतील सुकाणुनाशक वायू एकत्रित आणि संरचनेतील सुकाणुनाशक वायू समाविष्ट असलेल्या तंबूत उपचार करण्यासाठी संपूर्ण संरचना बंद करणे हा संपूर्ण संरचनेतील सुकाणुनाशक वायू एकत्रित आणि संरचनेतील सुकाणुनाशक वायू समाविष्ट असलेल्या तंबूत उपचार करण्यासाठी संपूर्ण संरचना बंद करणे हा एक महत्त्वाचा आणि विशिष्ट पैलू आहे.",
  },
  {
    sourceQueryId: 460404,
    passageId: "mr_p_014193",
    language: "mr",
    content: "पॅनोरॅमिक रेडिओग्राफमध्ये डाव्या प्रीमोलर-मोलर प्रदेशात एक सुस्पष्ट, कॉर्टिकेटेड, मल्टिलोक्युलर रेडिओल्युसेंट व्रण दिसून आला. गळू सबअरिओलर (२३%), इंट्रामॅमरी युनिलोक्युलर (१२%), किंवा इंट्रामॅमरी मल्टिलोक्युलर (६५%) आढळले.",
  },
  {
    sourceQueryId: 667552,
    passageId: "mr_p_015485",
    language: "mr",
    content: "एक विस्थापित गुडघा कसा होतो. जेव्हा गुडघा अंशतः त्याच्या स्थितीतून बाहेर पडतो, तेव्हा डॉक्टरांनी या स्थितीला सबलक्सेशन म्हणतात. अंशतः विस्थापित गुडघा हा पूर्वीच्या विस्थापनाचा किंवा गुडघा बाहेर सरकण्याच्या वारशाने मिळालेल्या प्रवृत्तीचा परिणाम असू शकतो. गुडघ्याखाली सूज आणि वेदना होऊ शकतात जेव्हा व्यक्ती गुडघा फिरवते किंवा पायर्‍या चढते. गुडघ्याच्या अस्थिरतेची भावना ही एक सामान्य तक्रार आहे. विस्थापित गुडघा विरुद्ध विस्थापित गुडघा असे म्हणतात. \"विस्थापित गुडघा (गुडघ्याऐवजी) हा बरे होण्याच्या दृष्टीने सर्वात आव्हानात्मक खेळाच्या दुखापतींपैकी एक आहे,\" असे जोशुआ हॅकेल, एमडी, गल्फ ब्रीज, फ्लोरिडा येथील अँड्र्यूज इन्स्टिट्यूटचे प्राथमिक सेवा क्रीडा वैद्यकीय संचालक म्हणतात.",
  },
  {
    sourceQueryId: 454795,
    passageId: "mr_p_016878",
    language: "mr",
    content: "याचा अर्थ असा की, जर दरवाजाची रुंदी ३२ इंच असेल, तर तुमच्याकडे ३२ इंच रुंद आणि ३२ इंच लांब स्वच्छ जागा असली पाहिजे जी बाथरूममध्ये जाता येईल. एकदा बाथरूममध्ये गेल्यानंतर, तुम्हाला शौचालय, सिंक, टब किंवा बिडेटसमोर किमान २१ इंच जागा लागेल आणि शॉवरसमोर २४ इंच जागा लागेल.",
  },
  {
    sourceQueryId: 1164551,
    passageId: "mr_p_018045",
    language: "mr",
    content: "डिस्कव्हरी वाहिनी डायरेक्ट टीव्हीवरील वाहिनी २७८ आहे. रिमोटवर, मेनूवर जा, नंतर शोज शोधा, नंतर डिस नावाच्या वाहिन्या डिस्कवर दिसतील. तुम्हाला हवी असलेली वाहिनी निवडा आणि तुम्ही तिथे आहात.",
  },
  {
    sourceQueryId: 628484,
    passageId: "mr_p_019439",
    language: "mr",
    content: "जर तुमच्या रिअल्टरने या महत्त्वाच्या मुद्द्यांचा उल्लेख केला नसेल, तर तुम्हाला स्वतः थोडे खोलवर शोध घ्यावे लागेल. #1. AOAO शुल्क (म्हणजे देखभाल शुल्क किंवा HOA शुल्क). हवाईमध्ये, प्रत्येक कॉन्डोमिनियम विकासासाठी AOAO (अपार्टमेंट मालकांचे संघटन) असणे आवश्यक आहे. हे संघटना कॉन्डोमिनियम कॉम्प्लेक्स चालवण्यासाठी आणि देखभाल करण्यासाठी जबाबदार असलेल्या कॉन्डोमिनियम मालकांनी बनलेले आहे. हवाईमध्ये, प्रत्येक कॉन्डोमिनियम विकासासाठी AOAO (अपार्टमेंट मालकांचे संघटन) असणे आवश्यक आहे. हे संघटना कॉन्डोमिनियम कॉम्प्लेक्स चालवण्यासाठी आणि देखभाल करण्यासाठी जबाबदार असलेल्या कॉन्डोमिनियम मालकांनी बनलेले आहे.",
  },
  {
    sourceQueryId: 485808,
    passageId: "mr_p_020740",
    language: "mr",
    content: "वस्तुस्थिती अशी आहे की आपल्याला चांगल्या आरोग्यासाठी स्वच्छ हवेची आवश्यकता आहे. जीवाश्म इंधने आपल्या आरोग्यासाठी वाईट का आहेत याचे मुख्य कारण म्हणजे त्यांचे ज्वलन झाल्याने कार्बन डाय ऑक्साइड आणि मोनॉक्साइड, सल्फर ऑक्साइड, नायट्रोजन ऑक्साइड आणि हायड्रोकार्बन यांसारखे अनेक अत्यंत हानिकारक वायू सोडले जातात. जीवाश्म इंधने ज्वलल्यावर जो वायू सोडला जातो तो सर्वात जास्त प्रमाणात सोडला जातो. खरेतर, वातावरणात सोडल्या जाणार्‍या कार्बन डाय ऑक्साइडचे प्रमाण आता १५० वर्षांपूर्वीच्या तुलनेत २५ टक्क्यांपेक्षा जास्त आहे. जीवाश्म इंधने वातावरणात नायट्रस ऑक्साइड आणि मिथेनच्या पातळीत वाढीस कारणीभूत आहेत.",
  },
  {
    sourceQueryId: 631612,
    passageId: "mr_p_021996",
    language: "mr",
    content: "एक खाते कार्यकारी काय करतो? खाते कार्यकारी दोन प्राथमिक कारणांसाठी अस्तित्वात आहेत: सध्याच्या ग्राहकांना आनंदी ठेवणे आणि नवीन ग्राहकांना आकर्षित करणे. जर तुम्हाला एकाधिक जबाबदाऱ्या सांभाळणे, विविध व्यक्तिमत्त्व प्रकारांसह काम करणे आणि विक्रीची गर्दी वाटणे आवडत असेल, तर खाते कार्यकारी म्हणून जीवन तुम्हाला चांगले शोभेल. शिवाय, ही एक अशी स्थिती आहे जी अनेक उद्योगांमध्ये दिसून येते, त्यामुळे तुम्हाला तुमचा कौशल्य संच वापरण्याची संधी मिळेल.",
  },
  {
    sourceQueryId: 195419,
    passageId: "mr_p_023257",
    language: "mr",
    content: "आमच्या संकेतस्थळाला भेट दिल्याबद्दल धन्यवाद. एम.डी. मधील कॅल्व्हर्ट काउंटीजवळ स्थित प्रिन्स फ्रेडरिकचे वाइनगार्डनर जी.एम.सी. ब्युक हे वॉशिंग्टन डी.सी. पासून केवळ काही मिनिटांच्या अंतरावर आहे, ज्यामुळे आम्ही तुमचे आघाडीचे नवीन आणि वापरलेले ब्युक जी.एम.सी. विक्रेते बनले आहोत. वाइनगार्डनरने कॅल्व्हर्ट काउंटी क्षेत्राला ब्युक आणि जी.एम.सी. देऊ शकणाऱ्या सर्वोत्तम सेवांसह सेवा दिली आहे. आम्ही आमच्या ग्राहकांसाठी विशेष आणि प्रोत्साहने देतो.",
  },
  {
    sourceQueryId: 500878,
    passageId: "mr_p_024477",
    language: "mr",
    content: "[शब्द: सोयाला, सोयाला] बाळिकेचे नाव सोयाला हे एस-ओवाय एए एलएएच † म्हणून उच्चारले जाते. सोयाला हे मूळ अमेरिकन मूळ असलेले नाव आहे. या नावाचा अर्थ हिवाळ्यातील संक्रांतीच्या काळात जन्मलेला असा होतो. सोयाला, सोयालिया, सोयालिया, सोयाला, आणि सोयाल्या हे सोयालाचे विविध प्रकार आहेत. सोयाला हे बाळिकेचे नाव म्हणून दुर्मिळ आहे. ते पहिल्या १००० मध्ये सूचीबद्ध नाही. सोयालासारखे नाव असलेल्या बाळिकांच्या नावांमध्ये सॅसिलिया, साहेला, साहेला, साहेला, साहेला, साहेले, साहिला, साहिला, साहिला, सैलिया, सलासिया, सलासिया, सलासिया, सलिया, सलिया, सलिहा, सलिहा, सलिहा, सलिया, सलिया, सलिया, सलिहा, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया, सलिया,",
  },
  {
    sourceQueryId: 670568,
    passageId: "mr_p_025807",
    language: "mr",
    content: "फोरेन्सिक मानसशास्त्रातील नोकऱ्यांसाठी तुम्हाला आवश्यक असलेल्या कौशल्यांमध्ये मजबूत संशोधन क्षमता, समीक्षात्मक विचार करण्याची कौशल्ये, कायदेशीर प्रणालीचे चांगले ज्ञान आणि ठोस बोललेले आणि लिखित संप्रेषण कौशल्ये यांचा समावेश होतो. या संशोधनाचा विशिष्ट विषय काही नावे घेण्यासाठी रोजगार कायदा, विमा दावा कायदा आणि कौटुंबिक कायदा यांचा समावेश करू शकतो. ठोस आणि कार्यक्षम संशोधन कौशल्ये सामान्यत: तुम्ही तुमच्या काही पहिल्या फोरेन्सिक मानसशास्त्र नोकऱ्यांसाठी अर्ज करता तेव्हा संभाव्य नियोक्ते विचारात घेतात त्या पहिल्या भरती निर्णय घटकांपैकी एक असतात.",
  },
  {
    sourceQueryId: 287004,
    passageId: "mr_p_027013",
    language: "mr",
    content: "अमेरिकेत कधीही दाखवले न गेलेल्या एका टीव्ही जाहिरातीत एडी मर्फीने टोयोटा सेडानच्या पुढच्या बंपरला चुंबन घेतले. त्याला आठ मुले आहेत. त्याचे पहिले आणि सर्वात मोठे अपत्य पॉलेट मॅकनीली: मुलगा, एरिक (१० जुलै १९८९ रोजी जन्मलेला) यांच्यासोबत होते.",
  },
  {
    sourceQueryId: 1185653,
    passageId: "mr_p_028228",
    language: "mr",
    content: "ए: हेलियम फुगे तरंगतात कारण ते सभोवतालच्या हवेपेक्षा कमी घन असतात, ज्यामुळे ते वर येतात. गुरुत्वाकर्षण हेलियम फुग्यांवर त्याच प्रकारे कार्य करते ज्याप्रमाणे ते सभोवतालच्या हवेवर करते; फुगा तरंगतो की नाही यावर त्याचा काही परिणाम होत नाही. हे सर्व सापेक्ष घनतेवर अवलंबून आहे.",
  },
  {
    sourceQueryId: 559641,
    passageId: "mr_p_029506",
    language: "mr",
    content: "ऑस्ट्रेलिया, जमैका आणि न्यू ऑर्लीन्समध्ये, हिरव्या कांद्यांना शॅलॉट्स म्हणतात. आणि, सर्वत्र, अनेक लोकांना हिरव्या कांद्यांना एकतर तरुण लीक्स, कांद्याचे वरचे भाग किंवा शॅलॉट्सचे खोड असतात. ऑस्ट्रेलिया, जमैका आणि न्यू ऑर्लीन्समध्ये, हिरव्या कांद्यांना शॅलॉट्स म्हणतात. आणि, सर्वत्र, अनेक लोकांना हिरव्या कांद्यांना एकतर तरुण लीक्स, कांद्याचे वरचे भाग किंवा शॅलॉट्सचे खोड असतात.",
  },
  {
    sourceQueryId: 612319,
    passageId: "mr_p_030941",
    language: "mr",
    content: "सांता क्लारा काउंटीचा समावेश सॅन जोसे-सनीवेल-सांता क्लारा, सी.ए. मेट्रोपॉलिटन स्टॅटिस्टिकल एरिया तसेच सॅन जोसे-सॅन फ्रान्सिस्को-ओकलँड, सी.ए. संयुक्त सांख्यिकी क्षेत्रामध्ये आहे.",
  },
  {
    sourceQueryId: 633259,
    passageId: "mr_p_032217",
    language: "mr",
    content: "कॉक्ससॅकी: तळहात आणि पायांवरील लहान लाल फोडांची अनेक कारणे असू शकतात. सामान्यतः विषाणूजन्य संसर्ग (कॉक्ससॅकी विषाणू) हात-पाय-तोंडाच्या आजाराला कारणीभूत ठरतो. उपचार हे लक्षणांसाठी आहे. इतर कारणे आहेत ज्यांना प्रतिजैविकांची आवश्यकता असते म्हणून तुमच्या डॉक्टरांना भेटा. ...अधिक वाचा.",
  },
  {
    sourceQueryId: 671397,
    passageId: "mr_p_033567",
    language: "mr",
    content: "आर्द्रता कोणत्या उपकरणाद्वारे मोजली जाते? आर्द्रता मोजणारे उपकरण हायग्रोमीटर म्हणून ओळखले जाते. हायग्रोमीटर हे एक उपकरण आहे जे हवेतील सापेक्ष आर्द्रता मोजते. हायग्रोमीटरचा एक सामान्य प्रकार म्हणजे सायक्रोमीटर, एक उपकरण जे ओल्या बल्ब आणि कोरड्या बल्बाचे तापमान एकाच वेळी मोजते.",
  },
  {
    sourceQueryId: 643494,
    passageId: "mr_p_034871",
    language: "mr",
    content: "1. परिस्थिती कमी करणे - (कायदा) एक परिस्थिती जी व्यक्तीला निर्दोष ठरवत नाही पण ज्यामुळे गुन्ह्याशी संबंधित शिक्षा कमी होते. विचार, परिस्थिती, स्थिती-माहिती जी निर्णय घेताना लक्षात ठेवली पाहिजे; दुसरा विचार म्हणजे त्यासाठी लागणारा वेळ.",
  },
  {
    sourceQueryId: 202260,
    passageId: "mr_p_036025",
    language: "mr",
    content: "आउटफिल्डर टाय कॉब, ज्याची कारकीर्द १९२८ मध्ये संपली, त्याची मेजर लीग बेसबॉल (एम.एल.बी.) च्या इतिहासातील सर्वोच्च फलंदाजीची सरासरी आहे. त्याने २४ हंगामांमध्ये बहुतांशी डेट्रॉईट टायगर्ससह .३६६ ची फलंदाजी केली. याव्यतिरिक्त, त्याने संपूर्ण हंगामात अमेरिकन लीगमध्ये बी.ए. साठी आघाडीचे राहून विक्रमी ११ फलंदाजीचे विजेतेपद पटकावले.",
  },
  {
    sourceQueryId: 527792,
    passageId: "mr_p_037144",
    language: "mr",
    content: "इटालियन लोक त्यांचे अन्न अतिशय गांभीर्याने घेतात. त्यामुळे त्यांच्या पाककृतींमध्ये घातलेल्या सर्व कामाचे कारण आहे. इटालियन लोक अनेक गोष्टी खातात ज्या सामान्यतः यू.के.मध्ये खाल्ल्या जात नाहीत, उदाहरणार्थ, गोगलगाय, घोडा, गाढव, साळ, शहामृग, गिनीपिग, ससा, जंगली डुक्कर, समुद्री अर्चिन, समुद्री गोगलगाय, ऑक्टोपस, स्क्विड, स्पॅरो, मोर इत्यादी. इटालियन लोक फक्त दूधाळ कॉफी पितात, जसे की कॅप्पुचिनो आणि कॅफेलेट, सकाळी नाश्त्यासाठी पहिल्यांदा.",
  },
  {
    sourceQueryId: 202822,
    passageId: "mr_p_038375",
    language: "mr",
    content: "सर्वोच्च न्यायालयाचे न्यायाधीश. सर्वोच्च न्यायालय हे देशातील सर्वोच्च न्यायालय आहे. त्यात एक मुख्य न्यायाधीश किंवा प्रमुख न्यायाधीश आणि आठ सहयोगी न्यायाधीश असतात. न्यायाधीशांची नियुक्ती राष्ट्रपतींद्वारे केली जाते आणि सेनेटच्या मताने मंजूर केली जाते. न्यायाधीश काँग्रेसद्वारे मंजूर केलेल्या कायद्यांचा अर्थ लावण्याचे काम करतात. आमचे सरकार स्थापन झाल्यापासून, एकशेहून अधिक न्यायाधीशांनी न्यायालयात काम केले आहे आणि अलीकडेपर्यंत, सर्व पुरुष होते. सँड्रा डे ओ'कॉनर ही सर्वोच्च न्यायालयात नियुक्त झालेली पहिली महिला होती. तिची नियुक्ती १९८१ मध्ये झाली होती.",
  },
  {
    sourceQueryId: 127220,
    passageId: "mr_p_039551",
    language: "mr",
    content: "सामाजिक परिस्थिती. सामाजिक परिस्थितीची व्याख्या: संकल्पनांचा एक संच जो व्यक्तीच्या सामाजिक वातावरणाशी संबंधित निकष किंवा क्रियाकलापांमुळे परिणामी होतो किंवा प्रभावित होतो. सामाजिक परिस्थिती हा संकल्पनात्मक अस्तित्व समूहाचा भाग आहे.",
  },
  {
    sourceQueryId: 494735,
    passageId: "mr_p_040722",
    language: "mr",
    content: "अर्धवाहक भौतिकशास्त्राच्या माहितीसाठी, अर्धवाहक पाहा. अर्धवाहक उपकरणे इलेक्ट्रॉनिक घटक आहेत जे अर्धवाहक सामग्रीच्या इलेक्ट्रॉनिक गुणधर्मांचा फायदा घेतात, प्रामुख्याने सिलिकॉन, जर्मेनियम आणि गॅलियम आर्सेनाइड, तसेच कार्बनिक अर्धवाहक. अर्धवाहक उपकरणांनी बहुतेक अनुप्रयोगांमध्ये थर्मिओनिक उपकरणांची (व्हॅक्यूम ट्यूब) जागा घेतली आहे. अर्धवाहक डायोड हे सामान्यत: एका पी-एन जंक्शनपासून बनवलेले उपकरण आहे. पी-प्रकार आणि एन-प्रकार अर्धवाहकाच्या जंक्शनवर एक डिप्लेशन प्रदेश तयार होतो जिथे मोबाइल चार्ज वाहकांच्या अभावामुळे प्रवाह प्रवाह रोखला जातो.",
  },
  {
    sourceQueryId: 285514,
    passageId: "mr_p_041949",
    language: "mr",
    content: "जॉनी डेप कॅसल होम्स. जॉनी डेप हा एक विपुल घरमालक आहे. त्याच्या सहा घरांची किंमत $२३ ते $१६ दशलक्ष आहे. त्याची कॅलिफोर्नियामध्ये चार घरे आहेत, संपूर्ण लॉस एंजेलिस आणि वेस्ट हॉलीवूडमध्ये - ज्यापैकी एक १९२७ सालचा परीकथासदृश किल्ला आहे.",
  },
  {
    sourceQueryId: 529333,
    passageId: "mr_p_043293",
    language: "mr",
    content: "आज बाजारात दोन प्रकारचे पोर्टेबल ऑक्सिजन सांद्रक उपलब्ध आहेत: सतत प्रवाह ऑक्सिजन सांद्रक आणि पल्स डोस किंवा आंतरायिक प्रवाह ऑक्सिजन सांद्रक. या दोन प्रकारच्या ऑक्सिजन प्रणालींचे फायदे आणि मर्यादा खूप वेगवेगळे आहेत आणि प्रत्येक रुग्णाच्या विशिष्ट प्रकारासाठी सर्वोत्तम आहे.",
  },
  {
    sourceQueryId: 655414,
    passageId: "mr_p_044607",
    language: "mr",
    content: "हार्वर्डमधील सरासरी जीपीए ४.०४ आहे. (बहुतांश शाळा ४.० पैकी वेटेड जीपीए वापरतात, जरी काही शाळा वेटेड नसलेले जीपीए दाखवतात. ४.०४ जीपीए असलेल्या हार्वर्डसाठी तुम्हाला तुमच्या वर्गात अव्वल असणे आवश्यक आहे. इतर अर्जदारांशी स्पर्धा करण्यासाठी तुम्हाला तुमच्या सर्व वर्गांमध्ये जवळजवळ सरळ ए गुण मिळवणे आवश्यक आहे. याव्यतिरिक्त, महाविद्यालयीन स्तरावरील शिक्षण हे सोपे आहे हे दाखवण्यासाठी तुम्ही एपी किंवा आयबी अभ्यासक्रमांसारखे कठीण वर्ग घ्यायला हवेत.",
  },
  {
    sourceQueryId: 719751,
    passageId: "mr_p_045759",
    language: "mr",
    content: "हातघाईची लढाई (हातघाईच्या लढाईकडून पुनर्निर्देशित) हातघाईची लढाई (कधीकधी एच.टी.एच. किंवा एच२एच म्हणून संक्षिप्त) ही दोन किंवा दोनपेक्षा अधिक व्यक्तींमधील अत्यंत कमी अंतरावर (ग्रॅपलिंग अंतर) घातक किंवा घातक नसलेली शारीरिक लढाई आहे ज्यामध्ये बंदुकांचा किंवा इतर अंतर शस्त्रांचा वापर समाविष्ट नाही.",
  },
  {
    sourceQueryId: 434794,
    passageId: "mr_p_046924",
    language: "mr",
    content: "जून २०१८ मध्ये कोडियाकमधील हवामान. जूनमध्ये कोडियाकमध्ये सरासरी ९ तास सूर्यप्रकाश असताना १३° से. दिवसा कमाल तापमान अपेक्षित आहे. २०१८ मध्ये अलास्कामध्ये तुमची पुढील सुट्टी बुक करण्यापूर्वी जूनमध्ये कोडियाकसाठी अधिक दीर्घकालीन हवामानाची सरासरी तपासा.",
  },
  {
    sourceQueryId: 6206,
    passageId: "mr_p_048164",
    language: "mr",
    content: "अनोऑक्सिजन आणि ऑक्सिजन या दोन्ही प्रकारच्या श्वसनाच्या पहिल्या टप्प्याला ग्लायकोलिसिस म्हणतात. ही प्रक्रिया एका ग्लुकोज (साखर) रेणूचे घेतल्यानंतर त्याला पायरुव्हेट आणि ऊर्जा (2 ATP) मध्ये तोडण्याची प्रक्रिया आहे. ऑक्सिजनयुक्त श्वसनादरम्यान आम्ही याबद्दल अधिक तपशीलवार चर्चा करू. अनोऑक्सिजनयुक्त श्वसनातील दुसऱ्या टप्प्याला किण्वन म्हणतात. किण्वन पायरुव्हेट (ग्लायकोलिसिसचा अंतिम उत्पादन) पासून सुरू होते. ग्लायकोलिसिस हा अनोऑक्सिजनयुक्त आणि ऑक्सिजनयुक्त दोन्ही प्रक्रियांसाठी पेशीय श्वसनातील पहिला टप्पा आहे. ग्लायकोलिसिस पेशीच्या सायटोसोलमध्ये होतो. सायटोसोलमध्ये आम्ही 1 ग्लुकोज रेणूला 2 पायरुव्हेट रेणूंमध्ये रूपांतरित करतो.",
  },
  {
    sourceQueryId: 1164236,
    passageId: "mr_p_049514",
    language: "mr",
    content: "परिधीय मज्जातंतूंमध्ये संयोजी ऊतकाचे तीन स्तर असतात: एपिन्यूरियम - हा संयोजी ऊतकाचा सर्वात बाह्य स्तर आहे जो ड्यूरा मेटरशी सतत जोडलेला असतो. यामध्ये मज्जातंतूच्या आतील कोणत्याही फॅसिकल्स (बंडल) मधील संयोजी ऊतक देखील समाविष्ट असते. पेरिन्यूरियम - हे अक्षतंतूंच्या फॅसिकलला वेढणारे संयोजी ऊतक आहे. एंडोन्यूरियम - हे वैयक्तिक अक्षतंतूंभोवती असलेले सूक्ष्म संयोजी ऊतक तंतू आहेत.",
  },
];
