import type { SourceDocument } from "./types";

/**
 * Generated from ai4bharat/MSMARCO-XI validation/hinval.parquet using
 * scripts/build_compact_validation_docs.py. All query, answer, and
 * passage values are verbatim upstream records.
 */
export const COMPACT_VALIDATION_DOCUMENTS: SourceDocument[] = [
  {
    queryId: 1102432,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: ". what is a corporation?",
    translatedQuery: "कॉर्पोरेशन क्या है?",
    englishAnswer: "A corporation is a company or group of people authorized to act as a single entity and recognized as such in law.",
    translatedAnswer: "निगम एक कंपनी या लोगों का समूह होता है जो एक एकल इकाई के रूप में कार्य करने के लिए अधिकृत होता है और कानून में इस प्रकार से मान्यता प्राप्त होती है।",
    englishPassage: "McDonald's Corporation is one of the most recognizable corporations in the world. A corporation is a company or group of people authorized to act as a single entity (legally a person) and recognized as such in law. Early incorporated entities were established by charter (i.e. by an ad hoc act granted by a monarch or passed by a parliament or legislature).",
    translatedPassage: "मैकडॉनल्ड कॉर्पोरेशन दुनिया के सबसे पहचानने योग्य निगमों में से एक है। एक निगम एक कंपनी या लोगों का समूह है जो एक एकल इकाई (कानूनी रूप से एक व्यक्ति) के रूप में कार्य करने के लिए अधिकृत है और कानून में इस तरह से मान्यता प्राप्त है। प्रारंभिक निगमित संस्थाएं चार्टर द्वारा स्थापित की गई थीं (अर्थात एक राजा द्वारा अनुदानित या संसद या विधायिका द्वारा पारित)।",
  },
  {
    queryId: 1035838,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what is the most participated sport worldwide",
    translatedQuery: "दुनिया भर में सबसे अधिक भाग लिया जाने वाला खेल क्या है",
    englishAnswer: "Football is the worlds most popular spectator sport.",
    translatedAnswer: "फुटबॉल दुनिया का सबसे लोकप्रिय दर्शक खेल है।",
    englishPassage: "Sport Fishing (angling) is the worlds most participative sport. Football is the worlds most popular spectator sport.",
    translatedPassage: "स्पोर्ट फिशिंग (एंगलिंग) दुनिया का सबसे अधिक भागीदारी वाला खेल है। फुटबॉल दुनिया का सबसे लोकप्रिय दर्शक खेल है।",
  },
  {
    queryId: 1021584,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what rock is a soapstone",
    translatedQuery: "साबुन का पत्थर कौन सा है",
    englishAnswer: "Soapstone is a type of Metamorphic Rocks.",
    translatedAnswer: "सोपस्टोन एक प्रकार की कायांतरित चट्टानें हैं।",
    englishPassage: "Soapstone is a type of Metamorphic Rocks. The color of rock is one of its important property. Soapstone rock is available in black, black to grey, green, grey colors. It is Dull, Banded and Foilated in appearance.",
    translatedPassage: "सोपस्टोन एक प्रकार की रूपांतरित चट्टान है। चट्टान का रंग इसकी महत्वपूर्ण विशेषताओं में से एक है। सोपस्टोन चट्टान काले, काले से धूसर, हरे, धूसर रंगों में उपलब्ध है। यह दिखने में सुस्त, पट्टेदार और फूला हुआ है।",
  },
  {
    queryId: 1005452,
    queryType: "NUMERIC",
    language: "hin_Deva",
    englishQuery: "when do girls stop gaining height",
    translatedQuery: "लड़कियाँ कब ऊँचाई प्राप्त करना बंद कर देती हैं",
    englishAnswer: "Girls stop growing height between the ages of 14 or 15 years, or a couple of years after menstruation begins.",
    translatedAnswer: "लड़कियों में 14 या 15 वर्ष की आयु के बीच या मासिक धर्म शुरू होने के कुछ वर्षों बाद लंबाई बढ़ना बंद हो जाता है।",
    englishPassage: "Girls grow at a quick pace throughout infancy and childhood. When they reach puberty, growth increases dramatically again. Girls stop growing and reach adult height usually between the ages of 14 or 15 years, or a couple of years after menstruation begins. Keep reading to learn more about this process, what to expect when it happens, and when you may want to call your child’s pediatrician.",
    translatedPassage: "बच्चियाँ पूरे शैशवावस्था और बचपन में तेजी से बढ़ती हैं। जब वे यौवन में पहुँचती हैं, तब विकास फिर से नाटकीय रूप से बढ़ता है। लड़कियाँ बढ़ना बंद कर देती हैं और आम तौर पर 14 या 15 साल की उम्र के बीच या मासिक धर्म शुरू होने के कुछ साल बाद वयस्क ऊँचाई तक पहुँच जाती हैं। इस प्रक्रिया के बारे में अधिक जानने के लिए आगे पढ़ें, जब ऐसा होता है तो क्या उम्मीद की जाए और कब आप अपने बच्चे के बाल रोग विशेषज्ञ से बात करना चाह सकते हैं।",
  },
  {
    queryId: 51014,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "benefits of midday naps",
    translatedQuery: "मध्याह्न नींद के लाभ",
    englishAnswer: "The brain's ability to learn may have deteriorated, may clear the brain's memory storage area and make room for new information.",
    translatedAnswer: "मस्तिष्क की सीखने की क्षमता खराब हो सकती है, मस्तिष्क के स्मृति भंडारण क्षेत्र को साफ कर सकती है और नई जानकारी के लिए जगह बना सकती है।",
    englishPassage: "The area of the brain that stores memories may get ''clogged up'' as the day goes on, akin to a full email in-box on your computer, he says. Napping at midday, when the brain's ability to learn may have deteriorated, may clear the brain's memory storage area and make room for new information, Walker says.",
    translatedPassage: "वे कहते हैं, दिन बीतने के साथ मस्तिष्क का वह क्षेत्र जो स्मृतियों को संग्रहीत करता है, उसमें रुकावट आ सकती है, जैसे कि आपके कंप्यूटर पर एक पूर्ण ईमेल-बॉक्स में होता है। दोपहर में झपकी लेने पर, जब मस्तिष्क की सीखने की क्षमता खराब हो सकती है, तो मस्तिष्क के स्मृति भंडारण क्षेत्र को साफ कर सकता है और नई जानकारी के लिए जगह बना सकता है।",
  },
  {
    queryId: 1087814,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what animals eat the diamond leaf willow located",
    translatedQuery: "कौन से जानवर हीरे की पत्ती खाते हैं वहाँ तक",
    englishAnswer: "Musk oxen, deer, desert sake, and dingos eat diamond leaf willow.",
    translatedAnswer: "कस्तूरी बैल, हिरण, रेगिस्तानी साके और डिंगो हीरे की पत्ती वाले विलो खाते हैं।",
    englishPassage: "What eats diamond leaf willow? Musk oxen, deer, desert sake, and dingos eat diamond leaf willow. The desert tortoise and diamond back rattlesnake eat diamond leaf willow too.",
    translatedPassage: "क्या हीरे की पत्ती वाले विलो को खाते हैं? कस्तूरी बैल, हिरण, रेगिस्तानी साके और डिंगो हीरे की पत्ती वाले विलो को खाते हैं। रेगिस्तानी कछुआ और हीरे की पीठ वाले रैटलस्नेक भी हीरे की पत्ती वाले विलो को खाते हैं।",
  },
  {
    queryId: 737071,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what is cyclopentasiloxane",
    translatedQuery: "साइक्लोपेंटासिलोक्सेन क्या है",
    englishAnswer: "It is a silicon-based cyclic compound.",
    translatedAnswer: "यह एक सिलिकॉन-आधारित चक्रीय यौगिक है।",
    englishPassage: "About CYCLOPENTASILOXANE: Cyclopentasiloxane (cyclomethicone) is a silicon-based cyclic compound; may be associated with environmental toxicity. Function(s): Hair Conditioning Agent; Skin-Conditioning Agent - Emollient; Solvent; SKIN CONDITIONING.",
    translatedPassage: "लगभग साइक्लोपेंटासिलोक्सेन: साइक्लोपेंटासिलोक्सेन (साइक्लोमेथिकोन) एक सिलिकॉन-आधारित चक्रीय यौगिक है; जो पर्यावरणीय विषाक्तता से जुड़ा हो सकता है। कार्य (कार्य): बाल अनुकूलन कारक; त्वचा-अनुकूलन कारक - मॉइस्चराइज़र; विलायक; त्वचा अनुकूलन।",
  },
  {
    queryId: 478356,
    queryType: "NUMERIC",
    language: "hin_Deva",
    englishQuery: "population of washoe county nv",
    translatedQuery: "वॉशो काउंटी एन.वी.ए. की आबादी",
    englishAnswer: "Total population of Washoe County, Nevada is 421,407.",
    translatedAnswer: "वाशो काउंटी, नेवादा की कुल जनसंख्या 421,407 है।",
    englishPassage: "Total population of WASHOE County, NV: 421,407: Male population of WASHOE County, NV: 212,744: Female population of WASHOE County, NV: 208,663: Median age (years) 37: White Population: 324,070: Black Population: 9,814: Indian Population: 7,209: Asian Population: 21,790: Hawaiian Population: 2,542: Hispanic Population: 93,724: Median age (Male) 36.3: Median age (Female) 37.7: Total households",
    translatedPassage: "डब्ल्यू.ए.एस.एच.ओ.ई. काउंटी, एन.वी.: 421,407: डब्ल्यू.ए.एस.एच.ओ.ई. काउंटी, एन.वी.: 212,744: डब्ल्यू.ए.एस.एच.ओ.ई. काउंटी, एन.वी.: 208,663: औसत आयु (वर्ष): 37: श्वेत आबादी: 324,070: अश्वेत आबादी: 9,814: भारतीय आबादी: 7,209: एशियाई आबादी: 21,790: हवाई आबादी: 2,542: हिस्पैनिक आबादी: 93,724: औसत आयु (पुरुष) 36.3: औसत आयु (महिला) 37.7: कुल परिवार",
  },
  {
    queryId: 1085549,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what county is garden valley, ca",
    translatedQuery: "कौन सी काउंटी बगीचा घाटी है का",
    englishAnswer: "Garden Valley is in El Dorado County, California.",
    translatedAnswer: "गार्डन वैली कैलिफोर्निया के एल डोराडो काउंटी में है।",
    englishPassage: "Garden Valley. Garden Valley (formerly, Johntown) is an unincorporated community in El Dorado County, California. It is located on Johntown Creek 6.25 miles (10 km) north-northwest of Chili Bar, at an elevation of 1949 feet (594 m).",
    translatedPassage: "गार्डन वैली: गार्डन वैली (पूर्व में, जॉनटाउन) कैलिफोर्निया के एल डोराडो काउंटी में एक अनिगमित समुदाय है। यह चिली बार से 6.25 मील (10 कि.मी.) उत्तर-उत्तर-पश्चिम में जॉनटाउन क्रीक पर 1949 फीट (594 मीटर) की ऊँचाई पर स्थित है।",
  },
  {
    queryId: 1085264,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what county is the city of helena alabama",
    translatedQuery: "हेलेना अलबामा शहर कौन सी काउंटी है",
    englishAnswer: "Helena is a city in Jefferson and Shelby Counties in the State of Alabama",
    translatedAnswer: "हेलेना अलबामा राज्य के जेफरसन और शेल्बी काउंटी का एक शहर है।",
    englishPassage: "Helena (pronunciation [3]) is a city in Jefferson and Shelby Counties in the State of Alabama. Helena is considered a suburb of Birmingham and part of the Birmingham-Hoover Metropolitan Area. As of the 2010 census the population was 16,793.",
    translatedPassage: "हेलेना (उच्चारण [3]) अलबामा राज्य के जेफरसन और शेल्बी काउंटी में एक शहर है। हेलेना को बर्मिंघम का उपनगर और बर्मिंघम-हूवर महानगरीय क्षेत्र का हिस्सा माना जाता है। 2010 की जनगणना के अनुसार जनसंख्या 16,793 थी।",
  },
  {
    queryId: 299401,
    queryType: "NUMERIC",
    language: "hin_Deva",
    englishQuery: "how many volts are outlets in the us?",
    translatedQuery: "हमारे अंदर कितने वोल्ट आउटलेट हैं?",
    englishAnswer: "110 to 120 volts",
    translatedAnswer: "110 से 120 वोल्ट तक",
    englishPassage: "In Canada and the United States, wall outlet voltage is standardized at 110 to 120 volts (anywhere in that range is considered OK). In Europe - most of the rest of the world…, actually - it is standardized at 220 volts.",
    translatedPassage: "कनाडा और संयुक्त राज्य अमेरिका में, दीवार आउटलेट वोल्टेज को 110 से 120 वोल्ट पर मानकीकृत किया जाता है (उस सीमा में कहीं भी इसे ठीक माना जाता है)। यूरोप में - दुनिया के अधिकांश हिस्सों में... वास्तव में - यह 220 वोल्ट पर मानकीकृत है।",
  },
  {
    queryId: 1084502,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what does a dba do for you",
    translatedQuery: "आपके लिए डी.बी.ए. क्या करता है",
    englishAnswer: "Database administrator make sure that data analysts can easily use the database to find the information they need and that the system performs as it should.",
    translatedAnswer: "डेटाबेस प्रशासक यह सुनिश्चित करता है कि डेटा विश्लेषक आवश्यक जानकारी प्राप्त करने के लिए डेटाबेस का आसानी से उपयोग कर सकें और प्रणाली जैसा काम करना चाहिए वैसा ही करे।",
    englishPassage: "What does a Database Administrator do? Database administrators, often called DBAs, make sure that data analysts can easily use the database to find the information they need and that the system performs as it should.",
    translatedPassage: "डेटाबेस प्रशासक क्या करता है? डेटाबेस प्रशासक, जिन्हें अक्सर डी.बी.ए. कहा जाता है, यह सुनिश्चित करते हैं कि डेटा विश्लेषक आवश्यक जानकारी प्राप्त करने के लिए डेटाबेस का आसानी से उपयोग कर सकें और प्रणाली जैसा काम करना चाहिए।",
  },
  {
    queryId: 731998,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what is coil wire on spark plug wire",
    translatedQuery: "स्पार्क प्लग वायर पर कॉइल वायर क्या होता है",
    englishAnswer: "Coil wire is a wire in older engines connecting ignition coil to the distributor.",
    translatedAnswer: "कॉइल वायर पुराने इंजनों में एक तार है जो इग्निशन कॉइल को वितरक से जोड़ती है।",
    englishPassage: "Older engines also have a wire connecting the ignition coil to the distributor, known as a coil wire. A coil wire is of the same construction as a spark plug wire, but generally shorter and with different terminals.",
    translatedPassage: "पुराने इंजनों में एक तार भी होती है जो इग्निशन कॉइल को वितरक से जोड़ती है, जिसे कॉइल वायर के रूप में जाना जाता है। कॉइल वायर स्पार्क प्लग वायर के समान निर्माण का होता है, लेकिन आम तौर पर छोटा और अलग-अलग टर्मिनलों के साथ।",
  },
  {
    queryId: 511002,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "teacher's aide",
    translatedQuery: "शिक्षक सहायक",
    englishAnswer: "They help a teacher in the classroom. They are not certified to teach themselves. Instead, aides work under the teacher's supervision to help students, grade papers and provide adult supervision during recess.",
    translatedAnswer: "वे कक्षा में एक शिक्षक की मदद करते हैं। वे खुद से पढ़ाने के लिए प्रमाणित नहीं हैं। इसके बजाय सहायक शिक्षक की देखरेख में छात्रों की मदद करने, कक्षा के कार्यों में सहायता करने और अवकाश के दौरान वयस्क पर्यवेक्षण प्रदान करने का काम करते हैं।",
    englishPassage: "1 What Courses Do You Take to Become a Teacher's Aide? As the name implies, teacher's aides help a teacher in the classroom. They are not certified to teach themselves. Instead, aides work under the teacher's supervision to help students, grade papers and provide adult supervision during recess. The job is flexible, as teacher's aides work only during the academic year. Qualifications vary by district, type of school and position.",
    translatedPassage: "1 शिक्षक सहायक बनने के लिए आप कौन से पाठ्यक्रम लेते हैं? जैसा कि नाम से पता चलता है, शिक्षक सहायक कक्षा में एक शिक्षक की मदद करते हैं। वे स्वयं पढ़ाने के लिए प्रमाणित नहीं हैं। इसके बजाय, सहायक शिक्षक की देखरेख में छात्रों की मदद करने, कागजात की ग्रेड करने और अवकाश के दौरान वयस्क पर्यवेक्षण प्रदान करने के लिए काम करते हैं। नौकरी लचीली है, क्योंकि शिक्षक सहायक केवल शैक्षणिक वर्ष के दौरान काम करते हैं। योग्यता जिले, स्कूल के प्रकार और पद के अनुसार भिन्न होती है।",
  },
  {
    queryId: 902488,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what temperture of oil to fry chicken wings",
    translatedQuery: "चिकन विंग्स तलने के लिए कितने तापमान का तेल चाहिए",
    englishAnswer: "375 degrees F (190 degrees C).",
    translatedAnswer: "375 डिग्री एफ (190 डिग्री सेल्सियस)।",
    englishPassage: "1 Heat the oil in a large skillet or deep fryer to 375 degrees F (190 degrees C). 2 Deep fry chicken wings in oil until done, about 10 minutes. 3 Remove chicken from skillet or deep fryer and drain on paper towels. 4 Melt the butter in a large skillet.",
    translatedPassage: "1. एक बड़े स्किलेट या डीप फ्रायर में तेल को 375 डिग्री एफ (190 डिग्री सी) पर गरम करें। 2. चिकन विंग्स को तेल में लगभग 10 मिनट तक पकाएं, जब तक कि वे पक न जाएं। 3. चिकन को स्किलेट या डीप फ्रायर से निकालें और पेपर टॉवल पर निकालें। 4. एक बड़े स्किलेट में मक्खन पिघलाएं।",
  },
  {
    queryId: 1048621,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "who plays storm in days of future past",
    translatedQuery: "जो भविष्य के दिनों में तूफान की तरह खेलता है",
    englishAnswer: "Halle Berry",
    translatedAnswer: "हैले बेरी",
    englishPassage: "Halle Berry plays Storm in the superhero film franchise Getty Images. Halle Berry’s role in the forthcoming X-Men film has been cut down to just one scene, according to reports.",
    translatedPassage: "सुपरहीरो फिल्म फ्रेंचाइजी गेटी इमेजेस में हेल बेरी ने स्टॉर्म की भूमिका निभाई है। रिपोर्ट्स के अनुसार आगामी एक्स-मेन फिल्म में हेल बेरी की भूमिका को केवल एक दृश्य तक सीमित कर दिया गया है।",
  },
  {
    queryId: 202747,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "highest point in allegheny county pa",
    translatedQuery: "एलेघेनी काउंटी में उच्चतम बिंदु पा",
    englishAnswer: "1,401 feet at River Hill in Forward Township.",
    translatedAnswer: "फॉरवर्ड टाउनशिप में रिवर हिल पर 1,401 फीट की ऊँचाई।",
    englishPassage: "From the highest point in Allegheny County, 1,401 feet at River Hill in Forward Township, to the 710 foot normal pool level of the Ohio River at the Point in Pittsburgh, and down to the 682 foot elevation on the banks of the Ohio as it exits the County in the west, the elevation varies by a bit more than 700 feet.",
    translatedPassage: "एलेघेनी काउंटी में सबसे ऊँचे स्थान से, फॉरवर्ड टाउनशिप में रिवर हिल पर 1,401 फीट से, पिट्सबर्ग में प्वाइंट पर ओहायो नदी के 710 फीट के सामान्य पूल स्तर तक, और पश्चिम में काउंटी से बाहर निकलने पर ओहायो के तट पर 682 फीट की ऊँचाई तक, ऊँचाई 700 फीट से थोड़ी अधिक है।",
  },
  {
    queryId: 981371,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "where is dijon france",
    translatedQuery: "डिजॉन फ्रांस कहाँ है",
    englishAnswer: "In the Burgundy region of France.",
    translatedAnswer: "फ्रांस के बरगंडी क्षेत्र में",
    englishPassage: "View More. Dijon, in the Burgundy region of France, known mostly by Americans for its mustard, offers the tourist many fine attractions. Dijon has a well-preserved medieval center and is the historic capital of the Burgundy wine region.",
    translatedPassage: "फ्रांस के बरगंडी क्षेत्र में स्थित डिजॉन, जिसे ज्यादातर अमेरिकियों द्वारा अपने सरसों के लिए जाना जाता है, पर्यटकों के लिए कई अच्छे आकर्षण प्रदान करता है। डिजॉन में एक अच्छी तरह से संरक्षित मध्ययुगीन केंद्र है और यह बरगंडी वाइन क्षेत्र की ऐतिहासिक राजधानी है।",
  },
  {
    queryId: 1091661,
    queryType: "NUMERIC",
    language: "hin_Deva",
    englishQuery: "phone number for iracing",
    translatedQuery: "दौड़ प्रतियोगिता के लिए फोन नंबर",
    englishAnswer: "781 271-1900 is the phone number for IRacing.",
    translatedAnswer: "781 271-1900 आई.आर.एस.ई.आई. का फोन नंबर है।",
    englishPassage: "Contact IRacing and Reviews How to contact IRacing and about IRacing ? IRacing address is 34 Crosby Dr Bedford, MA 01730-1449. United States. You can reach via mobile or landline through contact number (781) 271-1900. You can also reach there webite www.iracing.com and can get required information regarding to IRacing. If you as a customer of the IRacing. have any query, complaint, suggestion, feedback and reviews related to IRacing products and services then you can communicate through its customer detail.",
    translatedPassage: "IRacing संपर्क कैसे करें और समीक्षाएं कि IRacing संपर्क कैसे करें और IRacing के बारे में? IRacing का पता 34 क्रॉस्बी डॉ. बेडफोर्ड, एमए 01730-1449 है। संयुक्त राज्य अमेरिका। आप संपर्क नंबर (781) 271-1900 के माध्यम से मोबाइल या लैंडलाइन के माध्यम से पहुंच सकते हैं। आप वहां वेबसाइट www.iracing.com पर भी पहुंच सकते हैं और IRacing के बारे में आवश्यक जानकारी प्राप्त कर सकते हैं। यदि आप IRacing के ग्राहक हैं और IRacing उत्पादों और सेवाओं से संबंधित कोई प्रश्न, शिकायत, सुझाव, प्रतिक्रिया और समीक्षा चाहते हैं, तो आप इसके ग्राहक विवरण के माध्यम से संवाद कर सकते हैं।",
  },
  {
    queryId: 933861,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "what's the weather of qatar?",
    translatedQuery: "कतर का मौसम कैसा है?",
    englishAnswer: "A hot, dry desert climate with Temperature above 18°C.",
    translatedAnswer: "18 डिग्री सेल्सियस से अधिक तापमान के साथ गर्म, शुष्क रेगिस्तानी जलवायु।",
    englishPassage: "Koeppen-Geiger classification: the climate of Qatar can be classified as BWh climate; a hot, dry desert climate with the annual average Temperature above 18°C.",
    translatedPassage: "कोपेन-गीगेर वर्गीकरण: कतर की जलवायु को बी.डब्ल्यू.एच. जलवायु के रूप में वर्गीकृत किया जा सकता है; जिसमें वार्षिक औसत तापमान 18 डिग्री सेल्सियस से अधिक है।",
  },
  {
    queryId: 1023732,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "who are berbers",
    translatedQuery: "कौन बर्बर हैं",
    englishAnswer: "Berbers have reached high positions in the social hierarchy across the Maghreb.",
    translatedAnswer: "मग़रेब भर में सामाजिक पदानुक्रम में बर्बर उच्च पदों पर पहुँच गए हैं।",
    englishPassage: "Berbers have reached high positions in the social hierarchy across the Maghreb; good examples are the former president of Algeria, Liamine Zeroual, and the former prime minister of Morocco, Driss Jettou. Nevertheless, Berberists who openly show their political orientations rarely reach high hierarchical positions.",
    translatedPassage: "मग़रेब में सामाजिक पदानुक्रम में बर्बर उच्च पदों पर पहुँच चुके हैं; अल्जीरिया के पूर्व राष्ट्रपति लियामीन ज़ेरोउल और मोरक्को के पूर्व प्रधानमंत्री ड्रिस जेट्टौ इसके अच्छे उदाहरण हैं। फिर भी, जो बर्बर खुले तौर पर अपनी राजनीतिक अभिविन्यास दिखाते हैं, वे शायद ही कभी उच्च पदानुक्रमिक पदों पर पहुँचते हैं।",
  },
  {
    queryId: 1026860,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "who discovered aluminum and when",
    translatedQuery: "एल्यूमीनियम की खोज किसने की और कब?",
    englishAnswer: "Hans Christian Oersted in 1825.",
    translatedAnswer: "हंस क्रिश्चियन ओर्स्टेड 1825 में",
    englishPassage: "Aluminium was first isolated by Hans Christian Oersted in 1825 who reacted aluminium chloride (AlCl 3) with potassium amalgam (an alloy of potassium and mercury). Heating the resulting aluminium amalgam under reduced pressure caused the mercury to boil away leaving an impure sample of aluminium metal.",
    translatedPassage: "एल्यूमीनियम को पहली बार 1825 में हैंस क्रिश्चियन ऑर्स्टेड द्वारा अलग किया गया था, जिन्होंने एल्यूमीनियम क्लोराइड (एलसीएल 3) को पोटेशियम एमाल्गम (पोटेशियम और पारे का मिश्र) के साथ प्रतिक्रिया की थी। परिणामस्वरूप एल्यूमीनियम एमाल्गम को कम दबाव में गरम करने से पारा उबाल कर एल्यूमीनियम धातु का अशुद्ध नमूना छोड़ दिया गया।",
  },
  {
    queryId: 257022,
    queryType: "NUMERIC",
    language: "hin_Deva",
    englishQuery: "how long does it take to get medicare benefits after i apply",
    translatedQuery: "मेडिकेयर लाभ पाने में कितना समय लगता है अगर मैं आवेदन कर दूं।",
    englishAnswer: "Two years and five months for disability applicants.",
    translatedAnswer: "विकलांगता आवेदकों के लिए दो साल और पाँच महीने।",
    englishPassage: "But for disability applicants who apply for benefits only when they become disabled, and not before, the date that their Medicare coverage will start is more likely to be two years and five months after they apply for disability.",
    translatedPassage: "लेकिन विकलांगता आवेदकों के लिए, जो केवल तभी लाभ के लिए आवेदन करते हैं जब वे विकलांग हो जाते हैं, और इससे पहले नहीं, तो उनके मेडिकेयर कवरेज शुरू होने की तारीख दो साल और पाँच महीने बाद होने की संभावना है।",
  },
  {
    queryId: 65627,
    queryType: "DESCRIPTION",
    language: "hin_Deva",
    englishQuery: "can children have medical marijuana",
    translatedQuery: "क्या बच्चे चिकित्सीय मारिजुआना ले सकते हैं?",
    englishAnswer: "Yes, children have medical marijuana",
    translatedAnswer: "हाँ, बच्चों को मेडिकल मारिजुआना मिलता है।",
    englishPassage: "For the children with epilepsy who use medical marijuana, the strains often have an increase in cannabidiol, an ingredient that helps to treat the seizures. These strains are also non-psychoactive and low in THC, which is the part of marijuana that creates the “high” feeling.",
    translatedPassage: "चिकित्सीय मारिजुआना का उपयोग करने वाले मिर्गी से पीड़ित बच्चों के लिए, उपभेद में अक्सर कैनबिडिओल में वृद्धि होती है, एक घटक जो दौरे का इलाज करने में मदद करता है। ये उपभेद गैर-मनोविकारी भी होते हैं और टी.एच.सी. में कम होते हैं, जो मारिजुआना का वह हिस्सा है जो \"उच्च\" भावना पैदा करता है।",
  },
];
