import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.resolve(here, "../docs/diagnostics");
const raw = JSON.parse(fs.readFileSync(path.join(dir, "live-gateway-62-query-diagnostic.json"), "utf8"));
const labels = { A: "STT/transcription failure", B: "Language detection/filter failure", C: "Dense retrieval failure", D: "BM25 retrieval failure", E: "RRF/fusion failure", F: "Reranking failure", G: "Context sufficiency threshold too strict", H: "Extractive answer generation failure", I: "Grounding threshold too strict", J: "Dataset/index coverage limitation", K: "Other" };
const pct = value => `${(value * 100).toFixed(1)}%`;
const short = text => text && text.length > 240 ? `${text.slice(0, 237)}…` : text || "No passage returned";
const failures = raw.diagnostics.filter(item => item.failureCategory !== "SUCCESS" && item.failureCategory !== "PASS_REFUSAL");
const representative = failures.slice(0, 10);
const categoryRows = Object.entries(raw.summary.failureBreakdown).filter(([, count]) => count > 0).map(([category, count]) => `| ${category} | ${labels[category]} | ${count} |`).join("\n") || "| — | No classified failures | 0 |";
const sections = representative.map(item => {
  const top = item.rrfCandidates[0];
  const scores = top ? `dense: ${item.topDenseResults[0]?.score ?? "—"}; BM25: ${item.topSparseBm25Results[0]?.score ?? "—"}; RRF: ${top.score}` : "No hybrid candidate";
  return `### ${item.id} — ${item.failureCategory}: ${labels[item.failureCategory]}\n\n**Query:** ${item.originalQuery}\n\n**Language:** ${item.detectedLanguage}. **Embedding:** ${item.queryEmbeddingSuccess ? "success" : "failure"}. **Counts:** dense ${item.denseResultCount}, BM25 ${item.sparseBm25ResultCount}, RRF ${item.rrfCandidateCount}.\n\n**Top scores:** ${scores}. **Reranker/context/grounding:** ${item.rerankerScore} / ${item.contextSufficiencyScore} / ${item.groundingScore}.\n\n> ${short(top?.passage)}\n\n**Extractive candidates:** ${item.extractiveAnswerCandidates.map(candidate => `“${short(candidate.sentence)}” (${candidate.score})`).join("; ") || "none"}.\n\n**Final answer/refusal:** ${item.finalAnswer ?? "refusal"}`;
}).join("\n\n");
const markdown = `# Live Qdrant Hybrid Retrieval Coverage Diagnosis\n\n## Scope\n\nThis report executed ${raw.metadata.queryCount} typed English, Hindi, and Marathi queries against the **live external gateway** backed by ${raw.metadata.collection}. Every request used real multilingual E5 dense embeddings, Qdrant BM25 sparse search, RRF fusion, deterministic sentence reranking, context sufficiency, and extractive grounding. No LLM was used. The answerable cases use verified selected corpus passages with source query IDs 1185869, 1185868, and 150905 in all three languages.\n\n## Results\n\n| Metric | Result |\n|---|---:|\n| Queries | ${raw.metadata.queryCount} |\n| Correct evidence answers / all queries | ${raw.summary.correctEvidenceAnswerCount} / ${raw.metadata.queryCount} (${pct(raw.summary.successRate)}) |\n| Answerable-case success rate | ${raw.summary.correctEvidenceAnswerCount} / ${raw.summary.answerableQueryCount} (${pct(raw.summary.answerableSuccessRate)}) |\n| Refusals / all queries | ${raw.summary.refusalCount} / ${raw.metadata.queryCount} (${pct(raw.summary.refusalRate)}) |\n| Unsupported-query refusal rate | ${pct(raw.summary.unsupportedRefusalRate)} |\n| Retrieval recall@3 among known answerable cases | ${pct(raw.summary.retrievalRecallAt3)} |\n| Expected-answerable cases | ${raw.summary.answerableQueryCount} |\n\n## Failure categories\n\n| Category | Meaning | Count |\n|---|---|---:|\n${categoryRows}\n\n## Ten representative failures with real passages and scores\n\n${sections || "No failures were produced by this test."}\n\n## Smallest changes suggested by the measured gateway trace\n\nPreserve the current no-LLM architecture. Prioritize only the category counts above: add deterministic aliases for repeatable multilingual query variants, correct any language filter only when its traces exclude expected results, and calibrate context/grounding only for cases where the correct Qdrant candidate is already present but rejected. Do not lower global grounding thresholds to mask coverage gaps.\n`;
fs.writeFileSync(path.join(dir, "live-gateway-62-query-diagnostic-report.md"), `${markdown}\n`);
console.log(JSON.stringify({ report: path.join(dir, "live-gateway-62-query-diagnostic-report.md"), representativeFailureCount: representative.length }, null, 2));
